/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Reward:": "报酬：",
    "Reward: All other eternity challenge rewards are stronger.": "奖励：所有其他永恒挑战奖励更强。",
    "Reward: Boosts are cheaper.": "奖励：提升更便宜。",
    "Reward: Exponent to Infinity Generator": "奖励：无限生成器 的指数",
    "Reward: Exponent to infinity generator multipliers.": "奖励：无限生成器乘数的指数。",
    "Reward: Exponent to prestige power based on infinity stars (": "奖励：基于无限星的声望力量指数（",
    "Reward: Exponent to prestige power.": "奖励：声望力量的指数。",
    "Reward: Extra theorems.": "奖励：额外的定理。",
    "Reward: Faster Boost Autobuyer (triggering every game tick)": "奖励：更快的提升自动购买者（触发每个游戏滴答声）",
    "Reward: Faster Generator": "奖励：更快的发生器",
    "Reward: Infinity Autobuyer": "奖励：无限自动购买者",
    "Reward: Multiplier to all infinity generators based on time in infinity (": "奖励：基于无限时间的所有无限发生器的乘数（",
    "Reward: Multiplier to chroma cap.": "奖励：色度上限的乘数。",
    "Reward: Multiplier to eternity gain.": "奖励：永久收益的乘数。",
    "Reward: Multiplier to eternity generators.": "奖励：永恒生成器的乘数。",
    "Reward: Multiplier to Infinity Generator": "奖励：无限生成器的乘数",
    "Reward: Multiplier to infinity generators based on eternity points produced this complexity.": "奖励：基于永恒点的无限生成器的乘数产生了这种复杂性。",
    "Reward: Multiplier to infinity generators based on total infinity points produced this eternity.": "奖励：基于总无限点的无限生成器的乘数产生了这个永恒。",
    "Reward: Multiplier to normal generators based on stars.": "奖励：基于星星的普通生成器的乘数。",
    "Reward: Multiplier to per-purchase Eternity Generator": "奖励：每次购买的乘数永恒生成器",
    "Reward: Prestige Autobuyer": "奖励：声望自动购买者",
    "Reward: Sacrifice Autobuyer": "奖励：牺牲自动购买者",
    "Reward: Sacrifice is stronger.": "奖励：牺牲更强。",
    "Reward: The multiplier to generators based on total IP this eternity is uncapped.": "奖励：基于此永恒总 IP 的生成器乘数没有上限。",
    "Sacrifice Autobuyer": "牺牲自动购买者",
    "sacrifice multiplier multiplying Generator": "牺牲乘数乘法生成器",
    "Sacrifice no longer resets anything.": "牺牲不再重置任何东西。",
    "Sacrifice:": "牺牲：",
    "Sacrifice.": "牺牲。",
    "Unequip": "取消装备",
    "Unequip equipped powers and": "取消装备 已装备的力量和",
    "Unequip equipped powers on next complexity:": "取消装备 已装备的力量在下一个复杂性：",
    "Unequip equipped powers when loading a preset:": "加载预设时取消装备的力量：",
    "Unlock": "解锁",
    "Unlock a finality autobuyer.": "解锁最终自动购买者。",
    "Unlock a new color of chroma.": "解锁一种新的色度。",
    "Unlock an Infinity Generator": "解锁无限发生器",
    "Unlock autobuyers for power shard upgrades.": "解锁自动购买者以进行电源碎片升级。",
    "Unlock autobuyers for repeatable infinity upgrades.": "解锁自动购买者以进行可重复的无限升级。",
    "Unlock Chroma": "解锁色度",
    "Unlock chroma in Complexity Challenge": "在复杂性挑战中解锁色度",
    "Unlock chroma.": "解锁色度。",
    "Unlock equipped powers auto-load.": "解锁装备的力量自动加载。",
    "Unlock Galaxies": "解锁星系",
    "Unlock galaxies.": "解锁星系。",
    "Unlock Powers": "解锁权力",
    "Unlock powers.": "解锁权力。",
    "Unlock Slow Boost Autobuyer": "解锁慢速自动购买",
    "Unlock Slow Generator": "解锁慢速发生器",
    "Unlock study list auto-load.": "解锁学习列表自动加载。",
    "Unlock the Eternity Producer": "解锁永恒制作人",
    "Unlock the Eternity Producer.": "解锁永恒生产者。",
    "Unlock the Oracle": "解锁甲骨文",
    "Unlock the Oracle.": "解锁神谕。",
    "Unlocking chroma and colors:": "解锁色度和颜色：",
    "Unlocking galaxies will also give you autobuyers for complexity generators and power upgrades.": "解锁星系还将为您提供复杂性发生器和电力升级的自动购买者。",
    "Unlocking powers for the first time will also let you view the Oracle tab.": "首次解锁权力还可以让您查看 Oracle 选项卡。",
    "Unlocking powers will also let you gain your eternity points on eternity every second, without needing to eternity (EP generation).": "解锁能力还将让您每秒获得永恒点数，而无需永恒（EP 生成）。",
    "Unlocking the Eternity Producer for the first time will also let you view the Eternity Challenges tab.": "首次解锁 Eternity Producer 还会让您查看 Eternity Challenges 选项卡。",
    "Unlocking the Eternity Producer:": "解锁永恒生产者：",
    "Unlocking the Oracle for the first time will also let you view the Galaxies tab.": "首次解锁 Oracle 还可以查看 Galaxies 选项卡。",
    "unspent finality shard": "未使用的最终分片",
    "unspent theorem": "未使用定理",
    "up to a total times, then Study": "最多总次数，然后学习",
    "used for Complexity Challenge": "用于复杂性挑战",
    "View all": "查看全部",
    "View all complexity generators even if they would be otherwise invisible:": "查看所有复杂性生成器，即使它们本来是不可见的：",
    "View all eternity generators even if they would be otherwise invisible:": "查看所有永恒生成器，即使它们本来是不可见的：",
    "View all finality generators even if they would be otherwise invisible:": "查看所有最终生成器，即使它们本来是不可见的：",
    "View all infinity generators even if they would be otherwise invisible:": "查看所有无穷大生成器，即使它们本来是不可见的：",
    "View stars and generators anyway:": "无论如何查看星星和发生器：",
    "were equipped.": "配备。",
    "when entering infinity challenges:": "进入无限挑战时：",
    "When it's turned on again you'll get all the new auto-completed EC tiers at once.": "当它再次打开时，您将立即获得所有新的自动完成的 EC 层。",
    "will be dilated, making the galaxy effect have speed": "会膨胀，让星系效应有速度",
    "will trigger in": "将触发",
    "with": "和",
    "with all eternity challenges completed.": "完成所有永恒的挑战。",
    "with all normal challenges completed. (You also keep autobuyers and infinity remains broken.)": "完成所有正常挑战。 （您还保留了自动购买者，并且无穷大仍然被破坏。）",
    "with EP equal to your highest-ever number of boosts (": "EP 等于你有史以来最高的提升次数（",
    "with eternities based on your complexities (currently": "基于你的复杂性的永恒（目前",
    "with infinities based on your eternities (currently": "无限基于你的永恒（目前",
    "with infinity points based on your eternities (currently": "无限点基于你的永恒（目前",
    "with stars based on your eternities (currently": "与基于你永恒的星星（目前",
    "with time in complexity based on your finalities (currently": "根据您的最终结果（目前",
    "without sacrificing.": "不牺牲。",
    "Cost:": "成本：",
    "counts both those equipped and stored, but powers are never deleted while equipped.": "装备和储存的都计算在内，但装备时永远不会删除权力。",
    "Craft a power with type": "用类型制造力量",
    "Craft a power.": "制造力量。",
    "Crafted power": "精雕细琢的力量",
    "Crafting cost depends only on rarity (not on type), and is always at least twice the power shards gained from deletion.": "制作成本仅取决于稀有度（与类型无关），并且始终至少是从删除中获得的能量碎片的两倍。",
    "Create a finality preset": "创建最终性预设",
    "Create a power preset": "创建电源预设",
    "Create a preset": "创建预设",
    "Current effects of equipped powers:": "装备力量的当前效果：",
    "Current:": "当前的：",
    "Current: ^": "当前：^",
    "Current: +": "当前：+",
    "Current: Cost ^": "当前：成本 ^",
    "Currently all the syntax is visible.": "目前所有语法都是可见的。",
    "Currently:": "目前：",
    "Delete": "删除",
    "Delete (+": "删除 (+",
    "Despite this, the total cost of studies does not depend on the order you buy them in.": "尽管如此，学习的总成本并不取决于您购买它们的顺序。",
    "dilated, making the galaxy effect have speed": "膨胀，使星系效应有速度",
    "Display all goals:": "显示所有目标：",
    "Divide the complexity unlock requirements for complexity challenges by": "将复杂性挑战的复杂性解锁要求除以",
    "don't exist.)": "不存在。）",
    "Double per-boost multiplier": "双倍升压乘数",
    "due to complexities)": "由于复杂）",
    "due to finalities)": "由于最终结果）",
    "Due to unlocking galaxies, you have autobuyers for complexity generators and power upgrades.": "由于解锁了星系，您可以自动购买复杂性生成器和电源升级。",
    "Due to unlocking powers, you gain your eternity points on eternity every second, without needing to eternity (EP generation).": "由于解锁了力量，你每秒获得永恒点数，而无需永恒（EP 生成）。",
    "Each power raises all of a generator type's multipliers to a power. Up to": "每次幂都会将发电机类型的所有乘数提高到一次幂。取决于",
    "EC tier": "EC层",
    "effects are uncapped and raised ^": "效果没有上限和提高 ^",
    "equal to number of Generator": "等于发电机的数量",
    "Equip": "装备",
    "equipped power": "装备电源",
    "Equipped powers from the future:": "来自未来的装备力量：",
    "Equipped powers to constantly load:": "配备持续加载的电源：",
    "Equipped powers:": "装备力量：",
    "eternit": "永恒",
    "eternities": "永恒",
    "eternities in Complexity Challenge": "复杂性挑战中的永恒",
    "eternities to gain permanence.": "永恒以获得永恒。",
    "eternities,": "永恒，",
    "eternities.": "永恒。",
    "eternity": "永恒",
    "Eternity": "永恒",
    "Eternity Autobuyer": "永恒自动购买者",
    "Eternity Challenge": "永恒挑战",
    "eternity challenge (EC) tier": "永恒挑战 (EC) 层级",
    "Eternity challenge requirements and costs are removed, and you can complete multiple eternity challenge tiers at once.": "永恒挑战的要求和成本已被移除，您可以一次完成多个永恒挑战等级。",
    "eternity challenge tier": "永恒挑战等级",
    "eternity challenge tiers, without using automatic eternity challenge completion, in Complexity Challenge": "永恒挑战等级，不使用自动永恒挑战完成，在复杂性挑战中",
    "Eternity Challenges": "永恒的挑战",
    "Eternity challenges lock again once completed.": "永恒挑战完成后再次锁定。",
    "Eternity for": "永恒",
    "Eternity gain": "永恒的收获",
    "Eternity Generator": "永恒发电机",
    "Eternity generators are disabled.": "永恒生成器被禁用。",
    "Eternity generators are multiplied by": "永恒生成器乘以",
    "Eternity generators are multiplied by chroma": "永恒发生器乘以色度",
    "Eternity in": "永恒在",
    "Eternity in Complexity Challenge": "复杂性挑战中的永恒",
    "Eternity Milestone": "永恒里程碑",
    "Eternity Milestones": "永恒里程碑",
    "eternity point": "永恒点",
    "eternity points": "永恒点",
    "eternity points, without buying theorems, in Complexity Challenge": "永恒点，无需购买定理，在复杂性挑战中",
    "Eternity power extra multiplier": "永恒力量额外乘数",
    "Eternity Producer": "永恒制作人",
    "Eternity Producer base production per second:": "Eternity Producer 基础每秒产量：",
    "Eternity Producer multiplier to EGs:": "EG 的 Eternity Producer 乘数：",
    "eternity stars per second.": "每秒永恒的星星。",
    "eternity stars, multiplying all normal and infinity generators by": "永恒星，将所有法线和无穷大发生器乘以",
    "Eternity Upgrades:": "永恒升级：",
    "Eternity:": "永恒：",
    "Eternity: +": "永恒：+",
    "Eternity: Gain": "永恒：获得",
    "Eternity: requires": "永恒：需要",
    "Eternity.": "永恒。",
    "even if they would be otherwise invisible:": "即使它们本来是不可见的：",
    "even pre-complexity.": "甚至是复杂性。",
    "Every time you buy a": "每次买一个",
    "every time you prestige.": "每次你声望。",
    "Exit Infinity Challenge": "退出无限挑战",
    "Exit Normal Challenge": "退出正常挑战",
    "Export equipped powers": "出口装备力量",
    "Export finality shard upgrades": "导出最终分片升级",
    "Export studies": "出口研究",
    "Exported equipped powers (also copied to clipboard):": "导出的装备权力（也复制到剪贴板）：",
    "Exported finality shard upgrades (also copied to clipboard):": "导出的最终分片升级（也复制到剪贴板）：",
    "Exported studies (also copied to clipboard):": "导出的研究（也复制到剪贴板）：",
    "Exporting studies and preset study lists use the same syntax, which is explained below.\n          More of the syntax will be explained as it becomes useful.": "导出研究和预设研究列表使用相同的语法，如下所述。\n 更多语法将在有用时进行解释。",
    "Complexity and resets beyond complexity will reset eternity milestones, and will lock those milestones (including the ones saying \"Start each ... complexity\"), removing their effects until you unlock the milestones again. Once you start with enough eternities after complexity to start with eternity milestones unlocked, however, those milestones will have an effect even at the start of a complexity. This situation will also arise later in the game with other similar mechanics.": "复杂性和超越复杂性的重置将重置永恒里程碑，并将锁定那些里程碑（包括那些说“开始每个......复杂性”的里程碑），在您再次解锁里程碑之前消除它们的影响。 但是，一旦您在复杂性之后从足够的永恒开始以解锁永恒里程碑，即使在复杂性开始时，这些里程碑也会产生影响。 这种情况也会在游戏后期与其他类似机制一起出现。",
    "complexity": "复杂",
    "Complexity": "复杂",
    "complexity achievement": "复杂性成就",
    "Complexity Achievements": "复杂性成就",
    "complexity achievements unlocked:": "复杂性成就解锁：",
    "Complexity Autobuyer": "复杂性自动购买者",
    "complexity challenge": "复杂性挑战",
    "Complexity Challenge": "复杂性挑战",
    "Complexity challenge colors:": "复杂性挑战颜色：",
    "Complexity challenge rewards are currently": "复杂性挑战奖励目前是",
    "complexity challenge tier": "复杂性挑战层",
    "Complexity Challenges": "复杂性挑战",
    "complexity challenges.": "复杂性挑战。",
    "Complexity for": "复杂性",
    "Complexity Generator": "复杂性生成器",
    "Complexity in": "复杂性",
    "complexity point": "复杂点",
    "complexity points": "复杂点",
    "complexity stars per second.": "每秒复杂度星数。",
    "complexity stars this finality, making your complexity star factor": "复杂性成为这个终结的明星，使您的复杂性成为明星因素",
    "complexity stars, making all complexity challenge rewards": "复杂性之星，使所有复杂性挑战得到回报",
    "complexity stars.": "复杂性明星。",
    "complexity stars).": "复杂性星）。",
    "Complexity while in all": "总体上的复杂性",
    "Complexity:": "复杂：",
    "Complexity: +": "复杂性：+",
    "Complexity: Gain": "复杂性：增益",
    "Complexity: requires": "复杂性：需要",
    "Complexity.": "复杂。",
    "constantly increased to your current chroma.": "不断增加到您当前的色度。",
    "Copy export text:": "复制导出文本：",
    "Cost display:": "费用展示：",
    "cost increases are raised ^": "成本增加了^",
    "ℂP/sec,": "ℂP/秒,",
    "ℂP/second.": "ℂP/秒。",
    "Cyan": "青色",
    "Download export text:": "下载导出文本：",
    "Dull brown (": "暗褐色（",
    "Dull cyan (": "暗青色（",
    "Dull gold (": "暗金色（",
    "Dull green (": "暗绿色（",
    "Dull grey (": "暗灰色（",
    "Dull magenta (": "暗洋红 (",
    "Dull orange (": "暗橙色（",
    "Dull purple (": "暗紫色（",
    "Dull red (": "暗红色（",
    "Edge gradients:": "边缘渐变：",
    "EP while in Eternity Challenge": "在永恒挑战中的EP",
    "EP, and you unlock a complexity autobuyer.": "EP，你解锁了一个复杂的自动购买者。",
    "EP, giving": "EP，给予",
    "EP/sec,": "EP/秒，",
    "EP/second.": "EP/秒。",
    "extra galax": "额外的星系",
    "extra infinity point": "额外无穷大点",
    "Extra multiplier from complexity stars and time in complexity": "复杂度星的额外乘数和复杂度时间",
    "Extra multiplier from infinity stars": "来自无限星的额外乘数",
    "Extra multiplier from total strength and rarity of equipped powers": "装备力量的总强度和稀有性的额外乘数",
    "extra purchases.": "额外购买。",
    "extra star": "额外的星星",
    "extra theorem": "额外定理",
    "Extra theorems from green ^": "来自绿色的额外定理 ^",
    "Extra theorems:": "额外定理：",
    "Fast autobuyers": "快速自动购买者",
    "finalit": "最后",
    "finalities": "终局性",
    "finality": "终局性",
    "Finality": "确定性",
    "Finality Autobuyer": "确定性自动购买者",
    "Finality Generator": "确定性生成器",
    "Finality in": "终局性",
    "Finality Milestones": "最终里程碑",
    "finality point": "终结点",
    "Finality point gain on finality (": "终结点获得的终结点 (",
    "Finality presets (": "确定性预设 (",
    "finality presets. Delete existing presets to create more.": "最终性预设。删除现有预设以创建更多预设。",
    "finality shard": "最终分片",
    "finality shard upgrades can be bought up to": "最终分片升级最多可以购买",
    "Finality shard upgrades:": "最终分片升级：",
    "Finality Shards": "最终分片",
    "finality stars per second.": "每秒终结星数。",
    "finality stars, multiplying all non-finality generators by": "终结星，将所有非终结生成器乘以",
    "Finality:": "终局性：",
    "Finality: +": "确定性：+",
    "Finality: Gain": "终局性：增益",
    "Finality: requires": "终局性：需要",
    "Finality.": "终局性。",
    "for a long time.": "需很长时间。",
    "For galaxy effect and eternity power extra multipliers, you start each": "对于星系效应和永恒力量额外乘数，你开始每个",
    "for never):": "永不）：",
    "FP (maxed)": "FP（最大）",
    "FP and": "FP 和",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);