/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Reward:": "报酬：",
    "Reward: All other eternity challenge rewards are stronger.": "奖励：所有其他永恒挑战奖励更强。",
    "Reward: Boosts are cheaper.": "奖励：提升更便宜。",
    "Reward: Exponent to Infinity Generator": "奖励：无限生成器 的指数",
    "Reward: Exponent to infinity generator multipliers.": "奖励：无限生成器乘数的指数。",
    "Reward: Exponent to prestige power based on infinity stars (": "奖励：基于无限星的声望力量指数（",
    "Reward: Exponent to prestige power.": "奖励：声望力量的指数。",
    "Reward: Extra theorems.": "奖励：额外的定理。",
    "Reward: Faster Boost Autobuyer (triggering every game tick)": "奖励：更快的提升自动购买者（触发每个游戏滴答声）",
    "Reward: Faster Generator": "奖励：更快的发生器",
    "Reward: Infinity Autobuyer": "奖励：无限自动购买者",
    "Reward: Multiplier to all infinity generators based on time in infinity (": "奖励：基于无限时间的所有无限发生器的乘数（",
    "Reward: Multiplier to chroma cap.": "奖励：色度上限的乘数。",
    "Reward: Multiplier to eternity gain.": "奖励：永久收益的乘数。",
    "Reward: Multiplier to eternity generators.": "奖励：永恒生成器的乘数。",
    "Reward: Multiplier to Infinity Generator": "奖励：无限生成器的乘数",
    "Reward: Multiplier to infinity generators based on eternity points produced this complexity.": "奖励：基于永恒点的无限生成器的乘数产生了这种复杂性。",
    "Reward: Multiplier to infinity generators based on total infinity points produced this eternity.": "奖励：基于总无限点的无限生成器的乘数产生了这个永恒。",
    "Reward: Multiplier to normal generators based on stars.": "奖励：基于星星的普通生成器的乘数。",
    "Reward: Multiplier to per-purchase Eternity Generator": "奖励：每次购买的乘数永恒生成器",
    "Reward: Prestige Autobuyer": "奖励：声望自动购买者",
    "Reward: Sacrifice Autobuyer": "奖励：牺牲自动购买者",
    "Reward: Sacrifice is stronger.": "奖励：牺牲更强。",
    "Reward: The multiplier to generators based on total IP this eternity is uncapped.": "奖励：基于此永恒总 IP 的生成器乘数没有上限。",
    "Sacrifice Autobuyer": "牺牲自动购买者",
    "sacrifice multiplier multiplying Generator": "牺牲乘数乘法生成器",
    "Sacrifice no longer resets anything.": "牺牲不再重置任何东西。",
    "Sacrifice:": "牺牲：",
    "Sacrifice.": "牺牲。",
    "Unequip": "取消装备",
    "Unequip equipped powers and": "取消装备 已装备的力量和",
    "Unequip equipped powers on next complexity:": "取消装备 已装备的力量在下一个复杂性：",
    "Unequip equipped powers when loading a preset:": "加载预设时取消装备的力量：",
    "Unlock": "解锁",
    "Unlock a finality autobuyer.": "解锁最终自动购买者。",
    "Unlock a new color of chroma.": "解锁一种新的色度。",
    "Unlock an Infinity Generator": "解锁无限发生器",
    "Unlock autobuyers for power shard upgrades.": "解锁自动购买者以进行电源碎片升级。",
    "Unlock autobuyers for repeatable infinity upgrades.": "解锁自动购买者以进行可重复的无限升级。",
    "Unlock Chroma": "解锁色度",
    "Unlock chroma in Complexity Challenge": "在复杂性挑战中解锁色度",
    "Unlock chroma.": "解锁色度。",
    "Unlock equipped powers auto-load.": "解锁装备的力量自动加载。",
    "Unlock Galaxies": "解锁星系",
    "Unlock galaxies.": "解锁星系。",
    "Unlock Powers": "解锁权力",
    "Unlock powers.": "解锁权力。",
    "Unlock Slow Boost Autobuyer": "解锁慢速自动购买",
    "Unlock Slow Generator": "解锁慢速发生器",
    "Unlock study list auto-load.": "解锁学习列表自动加载。",
    "Unlock the Eternity Producer": "解锁永恒制作人",
    "Unlock the Eternity Producer.": "解锁永恒生产者。",
    "Unlock the Oracle": "解锁甲骨文",
    "Unlock the Oracle.": "解锁神谕。",
    "Unlocking chroma and colors:": "解锁色度和颜色：",
    "Unlocking galaxies will also give you autobuyers for complexity generators and power upgrades.": "解锁星系还将为您提供复杂性发生器和电力升级的自动购买者。",
    "Unlocking powers for the first time will also let you view the Oracle tab.": "首次解锁权力还可以让您查看 Oracle 选项卡。",
    "Unlocking powers will also let you gain your eternity points on eternity every second, without needing to eternity (EP generation).": "解锁能力还将让您每秒获得永恒点数，而无需永恒（EP 生成）。",
    "Unlocking the Eternity Producer for the first time will also let you view the Eternity Challenges tab.": "首次解锁 Eternity Producer 还会让您查看 Eternity Challenges 选项卡。",
    "Unlocking the Eternity Producer:": "解锁永恒生产者：",
    "Unlocking the Oracle for the first time will also let you view the Galaxies tab.": "首次解锁 Oracle 还可以查看 Galaxies 选项卡。",
    "unspent finality shard": "未使用的最终分片",
    "unspent theorem": "未使用定理",
    "up to a total times, then Study": "最多总次数，然后学习",
    "used for Complexity Challenge": "用于复杂性挑战",
    "View all": "查看全部",
    "View all complexity generators even if they would be otherwise invisible:": "查看所有复杂性生成器，即使它们本来是不可见的：",
    "View all eternity generators even if they would be otherwise invisible:": "查看所有永恒生成器，即使它们本来是不可见的：",
    "View all finality generators even if they would be otherwise invisible:": "查看所有最终生成器，即使它们本来是不可见的：",
    "View all infinity generators even if they would be otherwise invisible:": "查看所有无限生成器，即使它们本来是不可见的：",
    "View stars and generators anyway:": "无论如何查看星星和发生器：",
    "were equipped.": "配备。",
    "when entering infinity challenges:": "进入无限挑战时：",
    "When it's turned on again you'll get all the new auto-completed EC tiers at once.": "当它再次打开时，您将立即获得所有新的自动完成的 EC 层。",
    "will be dilated, making the galaxy effect have speed": "会膨胀，让星系效应有速度",
    "will trigger in": "将触发",
    "with": "和",
    "with all eternity challenges completed.": "完成所有永恒的挑战。",
    "with all normal challenges completed. (You also keep autobuyers and infinity remains broken.)": "完成所有正常挑战。 （您还保留了自动购买者，并且无限仍然被破坏。）",
    "with EP equal to your highest-ever number of boosts (": "EP 等于你有史以来最高的提升次数（",
    "with eternities based on your complexities (currently": "基于你的复杂性的永恒（目前",
    "with infinities based on your eternities (currently": "无限基于你的永恒（目前",
    "with infinity points based on your eternities (currently": "无限点基于你的永恒（目前",
    "with stars based on your eternities (currently": "与基于你永恒的星星（目前",
    "with time in complexity based on your finalities (currently": "根据您的最终结果（目前",
    "without sacrificing.": "不牺牲。",
    "Cost:": "成本：",
    "counts both those equipped and stored, but powers are never deleted while equipped.": "装备和储存的都计算在内，但装备时永远不会删除权力。",
    "Craft a power with type": "用类型制造力量",
    "Craft a power.": "制造力量。",
    "Crafted power": "精雕细琢的力量",
    "Crafting cost depends only on rarity (not on type), and is always at least twice the power shards gained from deletion.": "制作成本仅取决于稀有度（与类型无关），并且始终至少是从删除中获得的能量碎片的两倍。",
    "Create a finality preset": "创建最终性预设",
    "Create a power preset": "创建电源预设",
    "Create a preset": "创建预设",
    "Current effects of equipped powers:": "装备力量的当前效果：",
    "Current:": "当前的：",
    "Current: ^": "当前：^",
    "Current: +": "当前：+",
    "Current: Cost ^": "当前：成本 ^",
    "Currently all the syntax is visible.": "目前所有语法都是可见的。",
    "Currently:": "目前：",
    "Delete": "删除",
    "Delete (+": "删除 (+",
    "Despite this, the total cost of studies does not depend on the order you buy them in.": "尽管如此，学习的总成本并不取决于您购买它们的顺序。",
    "dilated, making the galaxy effect have speed": "膨胀，使星系效应有速度",
    "Display all goals:": "显示所有目标：",
    "Divide the complexity unlock requirements for complexity challenges by": "将复杂性挑战的复杂性解锁要求除以",
    "don't exist.)": "不存在。）",
    "Double per-boost multiplier": "双倍升压乘数",
    "due to complexities)": "由于复杂）",
    "due to finalities)": "由于最终结果）",
    "Due to unlocking galaxies, you have autobuyers for complexity generators and power upgrades.": "由于解锁了星系，您可以自动购买复杂性生成器和电源升级。",
    "Due to unlocking powers, you gain your eternity points on eternity every second, without needing to eternity (EP generation).": "由于解锁了力量，你每秒获得永恒点数，而无需永恒（EP 生成）。",
    "Each power raises all of a generator type's multipliers to a power. Up to": "每次幂都会将发生器类型的所有乘数提高到一次幂。取决于",
    "EC tier": "EC层",
    "effects are uncapped and raised ^": "效果没有上限和提高 ^",
    "equal to number of Generator": "等于发生器的数量",
    "Equip": "装备",
    "equipped power": "装备电源",
    "Equipped powers from the future:": "来自未来的装备力量：",
    "Equipped powers to constantly load:": "配备持续加载的电源：",
    "Equipped powers:": "装备力量：",
    "eternit": "永恒",
    "eternities": "永恒",
    "eternities in Complexity Challenge": "复杂性挑战中的永恒",
    "eternities to gain permanence.": "永恒以获得永恒。",
    "eternities,": "永恒，",
    "eternities.": "永恒。",
    "eternity": "永恒",
    "Eternity": "永恒",
    "Eternity Autobuyer": "永恒自动购买者",
    "Eternity Challenge": "永恒挑战",
    "eternity challenge (EC) tier": "永恒挑战 (EC) 层级",
    "Eternity challenge requirements and costs are removed, and you can complete multiple eternity challenge tiers at once.": "永恒挑战的要求和成本已被移除，您可以一次完成多个永恒挑战等级。",
    "eternity challenge tier": "永恒挑战等级",
    "eternity challenge tiers, without using automatic eternity challenge completion, in Complexity Challenge": "永恒挑战等级，不使用自动永恒挑战完成，在复杂性挑战中",
    "Eternity Challenges": "永恒的挑战",
    "Eternity challenges lock again once completed.": "永恒挑战完成后再次锁定。",
    "Eternity for": "永恒",
    "Eternity gain": "永恒的收获",
    "Eternity Generator": "永恒发生器",
    "Eternity generators are disabled.": "永恒生成器被禁用。",
    "Eternity generators are multiplied by": "永恒生成器乘以",
    "Eternity generators are multiplied by chroma": "永恒发生器乘以色度",
    "Eternity in": "永恒在",
    "Eternity in Complexity Challenge": "复杂性挑战中的永恒",
    "Eternity Milestone": "永恒里程碑",
    "Eternity Milestones": "永恒里程碑",
    "eternity point": "永恒点",
    "eternity points": "永恒点",
    "eternity points, without buying theorems, in Complexity Challenge": "永恒点，无需购买定理，在复杂性挑战中",
    "Eternity power extra multiplier": "永恒力量额外乘数",
    "Eternity Producer": "永恒制作人",
    "Eternity Producer base production per second:": "Eternity Producer 基础每秒产量：",
    "Eternity Producer multiplier to EGs:": "EG 的 Eternity Producer 乘数：",
    "eternity stars per second.": "每秒永恒的星星。",
    "eternity stars, multiplying all normal and infinity generators by": "永恒星，将所有法线和无限发生器乘以",
    "Eternity Upgrades:": "永恒升级：",
    "Eternity:": "永恒：",
    "Eternity: +": "永恒：+",
    "Eternity: Gain": "永恒：获得",
    "Eternity: requires": "永恒：需要",
    "Eternity.": "永恒。",
    "even if they would be otherwise invisible:": "即使它们本来是不可见的：",
    "even pre-complexity.": "甚至是复杂性。",
    "Every time you buy a": "每次买一个",
    "every time you prestige.": "每次你声望。",
    "Exit Infinity Challenge": "退出无限挑战",
    "Exit Normal Challenge": "退出正常挑战",
    "Export equipped powers": "出口装备力量",
    "Export finality shard upgrades": "导出最终分片升级",
    "Export studies": "出口研究",
    "Exported equipped powers (also copied to clipboard):": "导出的装备权力（也复制到剪贴板）：",
    "Exported finality shard upgrades (also copied to clipboard):": "导出的最终分片升级（也复制到剪贴板）：",
    "Exported studies (also copied to clipboard):": "导出的研究（也复制到剪贴板）：",
    "Exporting studies and preset study lists use the same syntax, which is explained below.\n          More of the syntax will be explained as it becomes useful.": "导出研究和预设研究列表使用相同的语法，如下所述。\n 更多语法将在有用时进行解释。",
    "Complexity and resets beyond complexity will reset eternity milestones, and will lock those milestones (including the ones saying \"Start each ... complexity\"), removing their effects until you unlock the milestones again. Once you start with enough eternities after complexity to start with eternity milestones unlocked, however, those milestones will have an effect even at the start of a complexity. This situation will also arise later in the game with other similar mechanics.": "复杂性和超越复杂性的重置将重置永恒里程碑，并将锁定那些里程碑（包括那些说“开始每个......复杂性”的里程碑），在您再次解锁里程碑之前消除它们的影响。 但是，一旦您在复杂性之后从足够的永恒开始以解锁永恒里程碑，即使在复杂性开始时，这些里程碑也会产生影响。 这种情况也会在游戏后期与其他类似机制一起出现。",
    "complexity": "复杂",
    "Complexity": "复杂",
    "complexity achievement": "复杂性成就",
    "Complexity Achievements": "复杂性成就",
    "complexity achievements unlocked:": "复杂性成就解锁：",
    "Complexity Autobuyer": "复杂性自动购买者",
    "complexity challenge": "复杂性挑战",
    "Complexity Challenge": "复杂性挑战",
    "Complexity challenge colors:": "复杂性挑战颜色：",
    "Complexity challenge rewards are currently": "复杂性挑战奖励目前是",
    "complexity challenge tier": "复杂性挑战层",
    "Complexity Challenges": "复杂性挑战",
    "complexity challenges.": "复杂性挑战。",
    "Complexity for": "复杂性",
    "Complexity Generator": "复杂性生成器",
    "Complexity in": "复杂性",
    "complexity point": "复杂点",
    "complexity points": "复杂点",
    "complexity stars per second.": "每秒复杂度星数。",
    "complexity stars this finality, making your complexity star factor": "复杂性成为这个终结的明星，使您的复杂性成为明星因素",
    "complexity stars, making all complexity challenge rewards": "复杂性之星，使所有复杂性挑战得到回报",
    "complexity stars.": "复杂性明星。",
    "complexity stars).": "复杂性星）。",
    "Complexity while in all": "总体上的复杂性",
    "Complexity:": "复杂：",
    "Complexity: +": "复杂性：+",
    "Complexity: Gain": "复杂性：增益",
    "Complexity: requires": "复杂性：需要",
    "Complexity.": "复杂。",
    "constantly increased to your current chroma.": "不断增加到您当前的色度。",
    "Copy export text:": "复制导出文本：",
    "Cost display:": "费用展示：",
    "cost increases are raised ^": "成本增加了^",
    "ℂP/sec,": "ℂP/秒,",
    "ℂP/second.": "ℂP/秒。",
    "Cyan": "青色",
    "Download export text:": "下载导出文本：",
    "Dull brown (": "暗褐色（",
    "Dull cyan (": "暗青色（",
    "Dull gold (": "暗金色（",
    "Dull green (": "暗绿色（",
    "Dull grey (": "暗灰色（",
    "Dull magenta (": "暗洋红 (",
    "Dull orange (": "暗橙色（",
    "Dull purple (": "暗紫色（",
    "Dull red (": "暗红色（",
    "Edge gradients:": "边缘渐变：",
    "EP while in Eternity Challenge": "在永恒挑战中的EP",
    "EP, and you unlock a complexity autobuyer.": "EP，你解锁了一个复杂的自动购买者。",
    "EP, giving": "EP，给予",
    "EP/sec,": "EP/秒，",
    "EP/second.": "EP/秒。",
    "extra galax": "额外的星系",
    "extra infinity point": "额外无限点",
    "Extra multiplier from complexity stars and time in complexity": "复杂度星的额外乘数和复杂度时间",
    "Extra multiplier from infinity stars": "来自无限星的额外乘数",
    "Extra multiplier from total strength and rarity of equipped powers": "装备力量的总强度和稀有性的额外乘数",
    "extra purchases.": "额外购买。",
    "extra star": "额外的星星",
    "extra theorem": "额外定理",
    "Extra theorems from green ^": "来自绿色的额外定理 ^",
    "Extra theorems:": "额外定理：",
    "Fast autobuyers": "快速自动购买者",
    "finalit": "最后",
    "finalities": "终局性",
    "finality": "终局性",
    "Finality": "确定性",
    "Finality Autobuyer": "确定性自动购买者",
    "Finality Generator": "确定性生成器",
    "Finality in": "终局性",
    "Finality Milestones": "最终里程碑",
    "finality point": "终结点",
    "Finality point gain on finality (": "终结点获得的终结点 (",
    "Finality presets (": "确定性预设 (",
    "finality presets. Delete existing presets to create more.": "最终性预设。删除现有预设以创建更多预设。",
    "finality shard": "最终分片",
    "finality shard upgrades can be bought up to": "最终分片升级最多可以购买",
    "Finality shard upgrades:": "最终分片升级：",
    "Finality Shards": "最终分片",
    "finality stars per second.": "每秒终结星数。",
    "finality stars, multiplying all non-finality generators by": "终结星，将所有非终结生成器乘以",
    "Finality:": "终局性：",
    "Finality: +": "确定性：+",
    "Finality: Gain": "终局性：增益",
    "Finality: requires": "终局性：需要",
    "Finality.": "终局性。",
    "for a long time.": "需很长时间。",
    "For galaxy effect and eternity power extra multipliers, you start each": "对于星系效应和永恒力量额外乘数，你开始每个",
    "for never):": "永不）：",
    "FP (maxed)": "FP（最大）",
    "FP and": "FP 和",
    "Max upgrades": "最大升级",
    "Minimum rarity of new powers:": "新能力的最低稀有度：",
    "Miscellaneous": "各种各样的",
    "Mixed Engineering": "混合工程",
    "Mixed Logarithm (Sci)": "混合对数 (Sci)",
    "Mixed Scientific": "混合科学",
    "Mode:": "模式：",
    "More colorful than a potato:": "比土豆更鲜艳：",
    "Move explanation back to the top of this tab": "将说明移回此选项卡的顶部",
    "Move explanation to the bottom of this tab": "将说明移至此选项卡的底部",
    "Move the above explanation back to the top of this tab": "将上述说明移回此选项卡的顶部",
    "Move the above explanation to the bottom of this tab": "将上述说明移至此选项卡底部",
    "Multiplier": "乘数",
    "multiplier based on stars (": "基于星星的乘数（",
    "multiplier is raised ^": "乘数提高^",
    "Multiplier per boost": "每次提升的乘数",
    "Multiplier softcap ^": "乘数软帽 ^",
    "Multiplier to boost power gain based on eternity challenge tiers completed (": "根据已完成的永恒挑战等级提高功率增益的乘数（",
    "Multiplier to chroma buildup speed (": "色度累积速度乘数 (",
    "Multiplier to chroma buildup speed based on eternities (currently": "基于永恒的色度累积速度乘数（目前",
    "Multiplier to chroma buildup speed based on total theorems": "基于总定理的色度累积速度乘数",
    "Multiplier to chroma cap (": "乘数到色度上限 (",
    "Multiplier to chroma cap based on theorems (currently": "基于定理的色度上限乘数（目前",
    "Multiplier to EGs based on total EP this complexity:": "基于总 EP 这个复杂性的 EG 乘数：",
    "Multiplier to eternity and permanence gain (": "永恒和永久增益的乘数 (",
    "Multiplier to eternity gain based on complexity achievements unlocked (": "基于解锁复杂性成就的永恒增益乘数（",
    "Multiplier to eternity gain based on eternity challenge tiers completed (": "基于完成的永恒挑战等级的永恒增益乘数（",
    "Multiplier to eternity gain:": "永恒收益的乘数：",
    "Multiplier to eternity generators based on eternity stars and time in eternity": "基于永恒之星和永恒时间的永恒生成器的乘数",
    "Multiplier to eternity generators based on prestige power": "基于声望力量的永恒生成器的乘数",
    "Multiplier to eternity generators based on total theorems": "基于总定理的永恒生成器的乘数",
    "Multiplier to galaxy effect buildup speed (": "星系效应累积速度乘数 (",
    "Multiplier to infinity generators based on eternities": "基于永恒的无限生成器的乘数",
    "Multiplier to infinity generators based on number of boosts": "基于提升次数的无限生成器的乘数",
    "Multiplier to infinity generators based on prestige power": "基于声望力量的无穷发生器的乘数",
    "Multiplier to infinity generators based on total color value": "基于总颜色值的无限生成器的乘数",
    "Multiplier to infinity generators based on total theorems": "基于总定理的无限生成器的乘数",
    "Multiplier to normal generators based on prestige power": "基于声望功率的普通发生器乘数",
    "Multiplier to normal generators based on total stars this complexity": "基于总星数的正常生成器的乘数这种复杂性",
    "Multiplier to normal generators based on total theorems": "基于总定理的正常生成器的乘数",
    "Multiplier to permanence based on eternity stars:": "基于永恒之星的永久性乘数：",
    "Multiplier to power gain speed (": "功率增益速度的乘数 (",
    "Multiplier to the per-boost multiplier based on eternities (currently": "基于永恒的每次提升乘数的乘数（目前",
    "multiplier.": "乘数。",
    "multiplier)": "乘数）",
    "multipliers are always": "乘数总是",
    "multipliers are reduced above": "乘数减少到上面",
    "multipliers in reverse order (G8 multiplier larger than G7 multiplier ... larger than G1 multiplier).": "逆序乘数（G8 乘数大于 G7 乘数...大于 G1 乘数）。",
    "multiplying all generators": "将所有生成器相乘",
    "multiplying permanence and chroma buildup speed by": "将持久性和色度累积速度乘以",
    "must be the first color you unlock.": "必须是您解锁的第一个颜色。",
    "Name:": "姓名：",
    "never auto-completing an EC tier": "从不自动完成 EC 层",
    "new power": "新势力",
    "New powers can be stored up by turning power gain off. When it's turned on again you'll get all the new powers at once.": "可以通过关闭功率增益来存储新的功率。当它再次打开时，您将立即获得所有新功能。",
    "New powers generally have a random type and random rarity.": "新异能一般具有随机类型和随机稀有度。",
    "News (non-game-relevant messages at top of screen):": "新闻（屏幕顶部与游戏无关的消息）：",
    "next": "下一个",
    "Next complexity": "下一个复杂性",
    "next finality.": "下一个结局。",
    "Next galaxies are at": "下一个星系在",
    "next in": "下一个",
    "Next power": "下一个权力",
    "Next theorem at": "下一个定理",
    "Next:": "下一个：",
    "No extra multiplier": "没有额外的乘数",
    "No requirement (you're always in this challenge).": "没有要求（你总是在这个挑战中）。",
    "None": "无",
    "normal": "普通的",
    "Normal": "普通的",
    "normal challenge": "正常挑战",
    "Normal Challenge": "普通挑战",
    "Normal Challenges": "正常挑战",
    "Normal Challenges:": "正常挑战：",
    "normal challenges.": "正常的挑战。",
    "Not on by default due to ℂP generation": "由于 ℂP 生成，默认情况下未启用",
    "Not on by default due to EP generation": "由于 EP 生成，默认情况下未启用",
    "Not on by default due to IP generation": "由于 IP 生成，默认情况下未启用",
    "Not on by default due to permanence generation": "由于永久生成，默认情况下未启用",
    "Notation on times:": "时间符号：",
    "Notation:": "符号：",
    "Note that you can put fourth-row studies (that is, numbers from 13 to 16) in this list, but there is a more convenient syntax for fourth-row studies explained below.": "请注意，您可以将第四行研究（即从 13 到 16 的数字）放在此列表中，但下面解释了第四行研究的更方便的语法。",
    "Note that you cannot benefit from the Eternity Producer or buy Eternity Producer upgrades before you unlock the Eternity Producer.": "请注意，在解锁 Eternity Producer 之前，您无法从 Eternity Producer 中受益或购买 Eternity Producer 升级。",
    "Note that you cannot gain chroma before you unlock any color of it, and": "请注意，在解锁任何颜色之前，您无法获得色度，并且",
    "Note that you cannot gain powers or buy power upgrades before you unlock powers.": "请注意，在解锁权力之前，您无法获得权力或购买权力升级。",
    "Note that you cannot get a prediction from the Oracle before you unlock the Oracle.": "请注意，在解锁 Oracle 之前，您无法从 Oracle 获得预测。",
    "Note that you cannot get any galaxies before galaxies are unlocked.": "请注意，在星系解锁之前，您无法获得任何星系。",
    "Number of achievements beyond last reached achievement to show:": "要显示的超出上一次达到的成就的成就数量：",
    "Number of last runs of each type to show:": "要显示的每种类型的最后运行次数：",
    "of each type are useless and are thus automatically deleted for power shards.": "每种类型的都是无用的，因此会被自动删除以用于 power shards。",
    "of every": "每一个",
    "of rarities.": "的稀有。",
    "Offline game ticks (between": "离线游戏滴答（之间",
    "Offline progress:": "离线进度：",
    "On:": "开启：",
    "Once you understand this explanation, you can move it to the bottom of this tab so that it doesn't take up so much space.": "一旦你理解了这个解释，你可以把它移到这个标签的底部，这样它就不会占用太多空间。",
    "Only achievements up to": "只有成就达到",
    "Options": "选项",
    "Options: cannot be hidden": "选项：不能隐藏",
    "Oracle": "甲骨文",
    "Loading the study list a,b,c,...,z tries to buy Study a, then Study b, then Study c, and so on, until it has bought Study z.\n          If the game cannot buy a study in the list with the available theorems, it will continue to the next study in the list rather than stopping.": "加载研究列表 a,b,c,...,z 尝试购买研究 a，然后研究 b，然后研究 c，依此类推，直到它购买研究 z。\n 如果游戏无法购买研究 与可用定理的列表，它将继续到列表中的下一个研究而不是停止。",
    "Import color scheme": "导入配色方案",
    "Import equipped powers": "进口装备电源",
    "Import finality shard upgrades": "导入最终分片升级",
    "Import studies": "导入研究",
    "Import tabs to show": "导入选项卡以显示",
    "Import/Load": "导入/加载",
    "in": "在",
    "in Complexity Challenge": "在复杂性挑战中",
    "In particular, when starting a new complexity, you will be in all complexity challenges that you've unlocked at once.": "特别是，当开始一个新的复杂性时，您将面临一次解锁的所有复杂性挑战。",
    "in this complexity, increasing chroma caps ^": "在这种复杂性中，增加色度上限 ^",
    "in this complexity.": "在这种复杂性中。",
    "in this complexity)": "在这种复杂性中）",
    "in this eternity, giving you": "在这永恒中，给你",
    "in this eternity.": "在这永恒中。",
    "in this eternity)": "在这永恒中）",
    "in this finality.": "在这个终结中。",
    "in this finality)": "在这个终结中）",
    "in this infinity.": "在这无限中。",
    "in this infinity)": "在这个无限中）",
    "in this prestige.": "在此声望。",
    "Increase the base multiplier per boost:": "增加每次提升的基础乘数：",
    "Increase the multiplier per boost:": "增加每次提升的乘数：",
    "Increase the per-purchase complexity generator multiplier based on best boost power (currently": "根据最佳升压功率增加每次购买的复杂度生成器乘数（目前",
    "Increase the per-purchase multiplier for EGs:": "增加 EG 的每次购买乘数：",
    "Increase the power of infinity stars:": "增加无限星的力量：",
    "Increase to strength of new powers (": "增加新力量的力量（",
    "increasing linearly from": "从线性增加",
    "infinit": "无限",
    "infinities.": "无限。",
    "infinity": "无穷",
    "Infinity": "无穷",
    "Infinity Autobuyer": "无限自动购买者",
    "infinity challenge": "无限挑战",
    "Infinity Challenge": "无限挑战",
    "Infinity Challenges": "无限挑战",
    "Infinity Challenges:": "无限挑战：",
    "Infinity Generator": "无限发生器",
    "Infinity generator multipliers are square-rooted (^": "无限生成器乘数是平方根 (^",
    "Infinity generator per-purchase multipliers are disabled.": "Infinity 生成器每次购买乘数被禁用。",
    "Infinity generators are disabled.": "无限发生器被禁用。",
    "Infinity in Infinity Challenge": "无限挑战中的无限",
    "Infinity in Normal Challenge": "正常挑战中的无限",
    "infinity point": "无限点",
    "infinity stars per second.": "每秒有无数颗星星。",
    "infinity stars, multiplying all": "无限的星星，乘以所有",
    "Infinity Upgrades:": "无限升级：",
    "Infinity:": "无穷：",
    "Infinity: +": "无限：+",
    "Infinity: Gain": "无限：增益",
    "Infinity: requires": "无限：需要",
    "Infinity.": "无穷。",
    "Instead, violating the condition makes you exit the challenge.": "相反，违反条件会让您退出挑战。",
    "Instead, violating the condition makes you exit the complexity challenge.": "相反，违反条件会使您退出复杂性挑战。",
    "into the future,": "走向未来，",
    "into the future, using": "未来，使用",
    "IP, giving": "知识产权，给予",
    "IP/sec,": "IP/秒，",
    "IP/second.": "IP/秒。",
    "is": "是",
    "is added to the multiplier per boost.": "每次提升都会添加到乘数中。",
    "It can also be used to see what powers you would gain with power gain on.": "它也可以用来查看在功率增益开启后你会获得什么功率。",
    "It can be improved via upgrades.": "它可以通过升级来改进。",
    "It is generally not recommended to delete any of your first few powers to get power shards.": "通常不建议删除前几个权力中的任何一个来获得权力碎片。",
    "It is impossible to get more than": "不可能超过",
    "It will also multiply all eternity generators by": "它还将所有永恒生成器乘以",
    "Keep already-obtained completions of each complexity challenge on": "保持每个复杂性挑战的已经完成",
    "Large fixed multiplier to normal generators": "普通发生器的大固定乘数",
    "Last complexity took": "最后的复杂性",
    "Last eternity took": "最后的永恒",
    "Last finality took": "最后的最终结果",
    "Last infinity took": "最后一个无限",
    "Last Ten Runs": "最后十次运行",
    "Last Ten Runs:": "最后十次运行：",
    "Letters": "信件",
    "Load": "加载",
    "log ℂP/sec,": "记录ℂP/秒，",
    "log ℂP/second.": "记录ℂP/秒。",
    "log EP/sec,": "记录 EP/秒，",
    "log EP/second.": "记录 EP/秒。",
    "log IP/sec,": "记录 IP/秒，",
    "log IP/second.": "记录 IP/秒。",
    "Logarithm": "对数",
    "Lose all but": "失去一切，但",
    "Magenta": "品红",
    "Main": "主界面",
    "Main:": "主要的：",
    "Make autobuyers trigger at most every X seconds (": "让自动购买者最多每 X 秒触发一次（",
    "making the finality generator per-purchase multiplier": "使最终生成器每次购买乘数",
    "Max": "最大限度",
    "Max all": "最大所有",
    "Max all normal generators and boosts": "最大化所有正常的发生器和助推器",
    "Max Eternity Producer upgrades": "Max Eternity Producer 升级",
    "Max fourth-row studies": "最大第四行研究",
    "Max generators": "最大发生器",
    "Max permanence upgrades": "最大永久升级",
    "Max power shard upgrades": "最大功率碎片升级",
    "Max power upgrades": "最大功率升级",
    "Oracle:": "甲骨文：",
    "Orange": "橘色",
    "other than Generator": "除了发生器",
    "permanence.": "永久性。",
    "permanence. You get": "永久性。你得到",
    "playing this game (counting time offline).": "玩这个游戏（离线计算时间）。",
    "playing this game (only counting time online).": "玩这个游戏（只计算在线时间）。",
    "power": "力量",
    "Power deletion:": "电源删除：",
    "Power gain in predictions:": "预测中的功率增益：",
    "Power gain:": "功率增益：",
    "power of each type but get more over time. You can have multiple powers of the same type equipped.": "每种类型的力量，但随着时间的推移会得到更多。您可以装备多个相同类型的力量。",
    "Power presets (": "电源预设（",
    "power presets. Delete existing presets to create more.": "电源预设。删除现有预设以创建更多预设。",
    "power shard": "电源分片",
    "Power shard upgrade multipliers take effect after power and rarity, but before extra multipliers.": "能量碎片升级乘数在能量和稀有度之后生效，但在额外乘数之前。",
    "power shards": "电源碎片",
    "Power shards can be used to buy upgrades that give powers small additional multipliers, and to craft new powers.": "能量碎片可用于购买赋予能量小的额外乘数的升级，以及制作新的能量。",
    "power shards.": "电源碎片。",
    "power shards)": "能量碎片）",
    "Power to Eternity Producer multiplier to EGs:": "EG 的 Eternity Producer 乘数：",
    "Power to fourth-row study effects based on per-boost multiplier (currently ^": "基于每次提升乘数的第四行研究效果的功效（目前 ^",
    "Power to non-finality generator multipliers (": "非确定性生成器乘数的功率（",
    "Power to third-row study effects:": "第三排研究效果的力量：",
    "Powers": "权力",
    "Powers are never destroyed unless you delete them, or unless they're automatically deleted as explained on this tab below stored powers.": "除非您删除它们，或者除非它们被自动删除，否则权力永远不会被破坏，如存储权力下方的此选项卡中所述。",
    "Powers can be equipped at any time as long as there is a free slot.": "只要有空位，就可以随时装备力量。",
    "Powers unequip:": "权力解除：",
    "Powers:": "权力：",
    "Pre-set locked reset autobuyers (this overrides the above setting):": "预设锁定重置自动购买者（这会覆盖上述设置）：",
    "Preset change:": "预设更改：",
    "Preset deletion:": "预设删除：",
    "Preset highlight colors:": "预设高亮颜色：",
    "Presets (": "预设（",
    "Presets can be used to load study lists more easily.": "预设可用于更轻松地加载研究列表。",
    "presets. Delete existing presets to create more.": "预设。删除现有预设以创建更多预设。",
    "Prestige Autobuyer": "威望自动购买者",
    "Prestige no longer resets anything.": "威望不再重置任何东西。",
    "Prestige power is raised ^": "威力提升^",
    "prestige power multiplying all": "威望力量倍增",
    "Prestige:": "声望：",
    "Prestige.": "声望。",
    "Prime": "主要的",
    "Produce": "生产",
    "purchases):": "购买）：",
    "purchases).": "购买）。",
    "Purple": "紫色的",
    "Rebuy studies when finishing ℂC6:": "完成ℂC6时重新购买研究：",
    "Red": "红色的",
    "Reload window": "重新加载窗口",
    "Reloading might work, so probably try that first.": "重新加载可能会起作用，所以可能先尝试一下。",
    "remaining": "其余的",
    "Remove the complexity unlock requirements for complexity challenges, and always have autobuyers for complexity generator and power upgrades.": "消除复杂性挑战的复杂性解锁要求，并始终为复杂性生成器和电源升级提供自动购买者。",
    "Remove this message": "删除此消息",
    "Remove this message for now": "暂时删除此消息",
    "Requirement to start:": "启动要求：",
    "Requirement to unlock:": "解锁要求：",
    "Reset buttons for hidden tabs:": "隐藏标签的重置按钮：",
    "Reset colors:": "重置颜色：",
    "Reset dilated galaxies to": "将膨胀的星系重置为",
    "Reset it (": "重置它（",
    "Reset it (exit and start again)": "重置它（退出并重新开始）",
    "RESET THE GAME": "重置游戏",
    "Respec eternity challenge and": "尊重永恒的挑战和",
    "Respec eternity challenge on next eternity:": "尊重下一个永恒的永恒挑战：",
    "Respec finality shard upgrades and": "尊重最终分片升级和",
    "Respec finality shard upgrades on next finality:": "Respec 在下一个 finality 上进行 finality 分片升级：",
    "Respec finality shard upgrades when loading a preset:": "加载预设时注意最终分片升级：",
    "Respec fourth-row studies and": "尊重第四行研究和",
    "Respec studies and": "尊重研究和",
    "Respec studies on next eternity:": "尊重下一个永恒的研究：",
    "Respec studies when loading a preset:": "加载预设时重新指定研究：",
    "Restart complexity and re-enter all complexity challenges": "重新启动复杂性并重新进入所有复杂性挑战",
    "Restart infinity challenges on completion:": "完成后重新启动无限挑战：",
    "Restart normal challenges on completion:": "完成后重新开始正常挑战：",
    "Return to default color scheme": "返回默认配色方案",
    "reward is instead currently": "奖励是目前",
    "reward strength and complexity star factor.": "奖励强度和复杂性明星因素。",
    "reward strength and total complexity stars are based on hypercomplexity stars, which are what your complexity stars would be if your complexity power": "奖励强度和总复杂性星基于超复杂性星，如果你的复杂性能力，这就是你的复杂性星",
    "Roman": "罗马",
    "Run types to show:": "要显示的运行类型：",
    "Save/load notifications:": "保存/加载通知：",
    "Scientific": "科学的",
    "scripts (should be 91).": "脚本（应该是 91）。",
    "second": "第二",
    "Seconds to reach cap": "达到上限的秒数",
    "Set craft rarity to maximum possible (": "将工艺稀有度设置为最大可能（",
    "Show (now unneeded) eternity challenge requirements:": "显示（现在不需要）永恒挑战要求：",
    "Show all unlocked tabs": "显示所有未锁定的标签",
    "Show color options": "显示颜色选项",
    "Show completed achievement rows:": "显示完成的成就行：",
    "Show explanation of presets and exported studies:": "显示预设和导出研究的说明：",
    "Show export reminder after X seconds (": "X 秒后显示导出提醒 (",
    "Show export text:": "显示导出文本：",
    "Show fully-question-mark achievement rows:": "显示全问号成就行：",
    "Show future power extra multipliers (as opposed to current):": "显示未来的功率额外乘数（相对于当前）：",
    "Show future powers on prediction:": "显示预测的未来力量：",
    "Show generator and boost autobuyers:": "显示生成器并提升自动购买者：",
    "Show other options": "显示其他选项",
    "Show saving options": "显示保存选项",
    "Show tab options": "显示选项卡选项",
    "Show waiting time from when prediction was made (as opposed to current):": "显示从做出预测开始的等待时间（相对于当前）：",
    "Single power unequip:": "单电源不装备：",
    "Single study refund:": "单次学习退款：",
    "Slow": "减缓",
    "Slow autobuyers will trigger in": "缓慢的自动购买者将触发",
    "Slow down offline progress (doing more ticks but being more accurate)": "减慢离线进度（做更多滴答但更准确）",
    "Smaller header:": "较小的标题：",
    "sort by name": "按名称分类",
    "Speed of gaining new powers:": "获得新能力的速度：",
    "Speed up offline progress (doing fewer ticks)": "加快离线进度（做更少的滴答声）",
    "square root of": "的平方根",
    "Standard": "标准",
    "stars": "星星",
    "stars per second.": "每秒星星。",
    "stars this complexity.": "明星这种复杂性。",
    "stars this eternity": "星辰这永恒",
    "stars this eternity.": "这个永恒的星星。",
    "stars this finality.": "明星这个结局。",
    "stars to infinity.": "星星到无限。",
    "stars.": "星星。",
    "stars. You are getting": "星星。你得到",
    "Start each": "开始每个",
    "Statistics:": "统计数据：",
    "stellar product and": "明星产品和",
    "Stored powers from the future:": "来自未来的储存力量：",
    "Stored powers:": "储存的力量：",
    "Strength of new powers:": "新势力的实力：",
    "Studies": "学习",
    "studies in Complexity Challenge": "复杂性挑战研究",
    "Studies on the fourth row are rebuyable, with increasing costs.": "第四行的研究是可重复购买的，但成本会增加。",
    "Studies respec:": "研究方面：",
    "Studies:": "学习：",
    "Study": "学习",
    "Study click mode:": "学习点击模式：",
    "Study list to constantly load:": "学习列表不断加载：",
    "Study list:": "学习清单：",
    "Swap your equipped powers with better stored powers of the same type and": "用相同类型的更好存储的力量交换你装备的力量和",
    "Synchronize slow and fast autobuyers": "同步慢速和快速自动购买者",
    "Tab colors:": "标签颜色：",
    "Tab presets (": "选项卡预设 (",
    "tab presets. Delete existing presets to create more.": "选项卡预设。删除现有预设以创建更多预设。",
    "Tabs to show:": "要显示的标签：",
    "Thanks to jdawson7 (clarifying strategy, improving guide), eQueline (suggesting many great QoL features), and Kyleptune (suggesting the ability to change colors).": "感谢 jdawson7（阐明策略、改进指南）、eQueline（提出了许多出色的 QoL 功能）和 Kyleptune（提出了改变颜色的能力）。",
    "Thanks to the testers (Boo, Dravitar, Earth, Omsi, Pichu, Sere, SpectralFlame, others, and Jazz) for testing before release and suggesting features.": "感谢测试人员（Boo、Dravitar、Earth、Omsi、Pichu、Sere、SpectralFlame、其他和 Jazz）在发布前进行测试并提出功能建议。",
    "Thanks to Universal Attractor (pre-infinity) and Antimatter Dimensions for game mechanics.": "感谢 Universal Attractor (pre-infinity) 和 Antimatter Dimensions 的游戏机制。",
    "The": "",
    "The ability to disable certain things is there to prevent accidental violation of complexity challenge requirements.": "禁用某些东西的能力是为了防止意外违反复杂性挑战要求。",
    "The calculation of which powers are the best": "计算哪种幂是最好的",
    "The complexity autobuyer is off when unlocked unless you explicitly pre-set it to be on.": "除非您明确将其预先设置为开启，否则复杂性自动购买器在解锁时会关闭。",
    "The Complexity Challenge": "复杂性挑战",
    "The complexity eight complexities ago took": "八个复杂性之前的复杂性",
    "The complexity five complexities ago took": "五个复杂性之前的复杂性",
    "The complexity four complexities ago took": "四个复杂度前的复杂度",
    "The complexity nine complexities ago took": "九个复杂性之前的复杂性",
    "The complexity seven complexities ago took": "七个复杂性之前的复杂性",
    "The complexity six complexities ago took": "六个复杂性之前的复杂性",
    "The complexity ten complexities ago took": "十个复杂性之前的复杂性",
    "The complexity three complexities ago took": "三个复杂性之前的复杂性",
    "The complexity two complexities ago took": "两个复杂性之前的复杂性",
    "The eternity eight eternities ago took": "八个永恒前的永恒",
    "The eternity five eternities ago took": "五个永恒前的永恒",
    "The eternity four eternities ago took": "四个永恒前的永恒",
    "The eternity nine eternities ago took": "九个永恒前的永恒",
    "The Eternity Producer is producing": "永恒制作人正在制作",
    "The Eternity Producer, when unlocked, will produce": "永恒生产者解锁后将生产",
    "The eternity seven eternities ago took": "七个永恒前的永恒",
    "The eternity six eternities ago took": "六个永恒前的永恒",
    "The eternity ten eternities ago took": "十个永恒前的永恒",
    "The eternity three eternities ago took": "三个永恒前的永恒",
    "The eternity two eternities ago took": "两个永恒前的永恒",
    "The finality eight finalities ago took": "八项终结前的终结",
    "The finality five finalities ago took": "五个结局前的结局",
    "The finality four finalities ago took": "最终确定性四个最终确定性采取了",
    "The finality nine finalities ago took": "九个结局前的结局",
    "The finality seven finalities ago took": "七项决赛前的决赛",
    "The finality six finalities ago took": "六年前的最终确定",
    "The finality ten finalities ago took": "十个结局前的结局",
    "The finality three finalities ago took": "三个结局前的结局",
    "The finality two finalities ago took": "两个结局前的结局",
    "The first": "首先",
    "The game is loading; this message should only appear for a few seconds.": "游戏正在加载；此消息应仅显示几秒钟。",
    "The header does not mention that you are in Complexity Challenge": "标题没有提到您在复杂性挑战中",
    "The infinity eight infinities ago took": "八无穷前的无限",
    "The infinity five infinities ago took": "无限五无限之前",
    "The infinity four infinities ago took": "四无穷前的无穷",
    "The infinity nine infinities ago took": "无穷九无穷之前",
    "The infinity seven infinities ago took": "无穷七无穷之前",
    "The infinity six infinities ago took": "无穷六无穷前取",
    "The infinity ten infinities ago took": "十无限前的无限",
    "The infinity three infinities ago took": "三个无限前的无限",
    "The infinity two infinities ago took": "两个无限之前的无限",
    "The multiplier to permanence and chroma from complexities also applies to boost power (currently": "复杂性对持久性和色度的乘数也适用于增强功率（目前",
    "The Oracle can look between": "Oracle 可以查看",
    "The Oracle is a quality-of-life feature that will let you see the future.": "Oracle 是一种生活质量功能，可让您看到未来。",
    "The Oracle lets you see what certain stats will be and what powers you will gain in the future.": "Oracle 让您了解某些统计数据以及您将来将获得哪些权力。",
    "The page loads": "页面加载",
    "The powers equipped by importing powers will be the strongest stored powers of the chosen types.": "导入异能所装备的异能将是所选类型中最强的储存异能。",
    "The prestige power formula alternates between being raised ^": "威能公式在被提升之间交替进行^",
    "The prestige power formula is worse the more prestiges you do.": "你做的声望越多，声望力量公式就越差。",
    "The value of whatever color you are producing is": "您生产的任何颜色的价值是",
    "The values of all colors are": "所有颜色的值都是",
    "Their costs are unaffected by buying other studies. Their shown costs are always the cost of the next purchase.": "他们的成本不受购买其他研究的影响。他们显示的成本始终是下一次购买的成本。",
    "times; the other": "次；另一个",
    "times.": "次。",
    "to": "至",
    "to always trigger):": "总是触发）：",
    "to avoid clutter, since you are always in it.": "避免混乱，因为你总是在里面。",
    "To complete a normal challenge, infinity while in the normal challenge.": "完成一次普通挑战，在普通挑战中无限。",
    "To complete an eternity challenge, eternity while in the eternity challenge. Completing or respeccing an eternity challenge will give all theorems spent on it back.": "完成一个永恒的挑战，永恒的同时在永恒的挑战中。完成或尊重永恒的挑战将使所有花费在它上面的定理都回来。",
    "To complete an infinity challenge, infinity while in the infinity challenge.": "完成一个无限挑战，在无限挑战中无限。",
    "to complexity.": "到复杂性。",
    "to prestige.": "声望。",
    "to sacrifice.": "牺牲。",
    "Toggle all autobuyers": "切换所有自动购买者",
    "total": "全部的",
    "total complexity point": "总复杂度点",
    "total complexity points to finality.": "总复杂性指向最终性。",
    "Total cost of": "总成本",
    "Total cost:": "总消耗：",
    "total ℂP this finality.": "总ℂP这个确定性。",
    "total EP.": "总EP。",
    "total eternity challenge tiers completed:": "完成的永恒挑战总层数：",
    "total eternity point": "总永恒点",
    "total eternity stars this finality, making your eternity star factor": "总永恒之星这个终局，使你的永恒之星因素",
    "total finality point": "总终结点",
    "total finality shard": "总终结性分片",
    "total finality shard upgrade purchase": "总确定性分片升级购买",
    "total infinity point": "总无穷点",
    "total infinity points to eternity.": "总无限指向永恒。",
    "total infinity stars this finality, making your infinity star factor": "总无穷星这个终结，使你的无穷星因子",
    "total powers (equipped and stored powers, not counting deleted powers).": "总权力（装备和储存的权力，不包括删除的权力）。",
    "total stars this finality, making your star factor": "总星这个结局，让你的明星因素",
    "total stars.": "总星数。",
    "total theorem": "总定理",
    "Total theorems:": "总定理：",
    "total this complexity,": "总的这种复杂性，",
    "total this eternity,": "总共这永恒，",
    "total this finality,": "总的这个结局，",
    "total,": "全部的，",
    "trigger every tick.": "触发每个滴答声。",
    "Turn all autobuyers off": "关闭所有自动购买者",
    "Turn all autobuyers on": "开启所有自动购买",
    "Turn all autobuyers on/off": "打开/关闭所有自动购买者",
    "Turn newly unlocked autobuyers on when unlocked:": "解锁时打开新解锁的自动购买：",
    "Turn on anyway:": "无论如何打开：",
    "Turning auto-EC completion on would complete": "打开自动 EC 完成将完成",
    "Turning power gain on would give you": "打开功率增益会给你",
    "unknown": "未知",
    "Untitled": "无标题",
    "Use base for AB settings": "使用基数进行 AB 设置",
    "Use tab groups": "使用选项卡组",
    "uses autobuyer settings.": "使用自动购买设置。",
    "Usual digits of precision:": "常用的精度位数：",
    "Vibrant": "充满活力",
    "Vibrant brown (": "充满活力的棕色 (",
    "Vibrant cyan (": "鲜艳的青色（",
    "Vibrant gold (": "充满活力的黄金（",
    "Vibrant green (": "充满活力的绿色（",
    "Vibrant grey (": "充满活力的灰色 (",
    "Vibrant magenta (": "充满活力的洋红色 (",
    "Vibrant orange (": "充满活力的橙色（",
    "Vibrant purple (": "充满活力的紫色（",
    "Vibrant red (": "鲜艳的红色（",
    "Vibrant yellow (": "充满活力的黄色（",
    "White": "白色的",
    "x (maxed)": "x（最大）",
    "x (the multiplier softcap).": "x（乘数软帽）。",
    "x and cap": "x 和上限",
    "x each).": "x 每个）。",
    "x faster.": "x 更快。",
    "x stronger (from": "x 更强（从",
    "x stronger.": "x 更强。",
    "X times best of last ten": "过去十次中最好的 X 次",
    "X times last": "最后 X 次",
    "x, and prestige power is raised ^": "x，威望提升^",
    "x, Next:": "x，下一个：",
    "Yellow": "黄色",
    "You": "你",
    "You always have autobuyers for eternity upgrades, eternity generators, and Eternity Producer upgrades, and you get autobuyers for theorems, permanence, and permanence upgrades.": "你总是有自动购买者用于永恒升级、永恒生成器和永恒生产者升级，你也会获得自动购买者用于定理、持久性和持久性升级。",
    "You are generating": "你正在生成",
    "You are getting": "你得到",
    "You auto-complete an EC tier once every": "您每自动完成一次 EC 层",
    "you buy gives you": "你买给你",
    "You can complete Complexity Challenge": "您可以完成复杂性挑战",
    "You can create at most": "您最多可以创建",
    "You can infinity at most": "你最多可以无限",
    "You can make some of your galaxies dilated to make the galaxy effect increase faster, but have a lower cap.": "您可以使某些星系膨胀以使星系效应增加得更快，但上限较低。",
    "Gold": "金子",
    "Green": "绿色的",
    "Grey": "灰色的",
    "Grey chroma powers purple and orange chroma effects (currently ^": "灰色色度为紫色和橙色色度效果提供动力（目前 ^",
    "Guide": "指导",
    "Have": "有",
    "Have all": "拥有所有",
    "Have all the first-row studies at once.": "一次完成所有第一行研究。",
    "Have all the studies in the first three rows at once.": "一次完成前三行的所有研究。",
    "Have at least": "至少有",
    "Have autobuyers for all": "为所有人提供自动购买者",
    "Have some generator multiplier over": "有一些生成器乘数",
    "Have the eternity power extra multiplier reach its cap (which is": "让永恒力量额外乘数达到其上限（即",
    "Have the time for the galaxy effect to cap be at least": "至少有时间让星系效应达到上限",
    "Header reset buttons:": "标题重置按钮：",
    "This base is used for displaying the values of the mantissa and exponent, so if it's 2 and the exponent base is 10, 1e10 is 100. It must be between 2 and 36. If you surround it in quotes or dashes, it'll be used as a list of digits rather than a base.": "这个底数用于显示尾数和指数的值，所以如果它是 2 并且指数底数是 10，则 1e10 是 100。它必须在 2 到 36 之间。如果你用引号或破折号将它括起来，它将是 用作数字列表而不是基数。",
    "Adding |ux to the end of a study list (where the u is a literal u) will keep at least x theorems unspent by studies no matter what. It's fine if those theorems are spent on an eternity challenge.\n          |cx is like |ux, except it uses the cost of Eternity Challenge x rather than the value of x. This is useful for eternity challenges.\n          Adding ! to a preset with |x will try to unlock the eternity challenge, and adding !! will try to start it. Additional exclamation marks have no additional effect.\n          When you have an eternity challenge unlocked and export a study list, that study list will have |cx!, where x is the eternity challenge, and it will have |cx!! if you are in the eternity challenge.": "将 |ux 添加到研究列表的末尾（其中 u 是文字 u）无论如何都会保持至少 x 个定理未被研究使用。 如果将这些定理用于永恒挑战，那很好。\n |cx 类似于 |ux，不同之处在于它使用永恒挑战 x 的成本而不是 x 的值。 这对于永恒挑战很有用。\n 添加 ! 到带有 |x 的预设将尝试解锁永恒挑战，并添加 !! 将尝试启动它。 额外的感叹号没有额外的效果。\n 当您解锁永恒挑战并导出研究列表时，该研究列表将带有 |cx!，其中 x 是永恒挑战，它将带有 |cx!! 如果你在永恒的挑战中。",
    "Hello you are playing FE00000. The news ticker factory didn't have enough budget for the extra 0.": "您好，您正在玩​​ FE00000。新闻自动收报机工厂没有足够的预算来支付额外的 0。",
    "Higher digits of precision": "更高的精度位数",
    "Hotkeys:": "热键：",
    "How to complete them is explained at the bottom of this tab.": "此选项卡底部说明了如何完成它们。",
    "However, no two consecutive new powers can have the same type or both have a rarity in the bottom": "但是，没有两个连续的新势力可以拥有相同的类型或两者都在底部稀有",
    "However, studies in this row can only be bought if all studies above are bought.": "但是，只有购买了上述所有研究，才能购买该行的研究。",
    "However, they can only be bought if all studies above are bought.": "但是，只有购买了上述所有研究，才能购买它们。",
    "hyper": "超",
    "hypercomplexity stars,": "超复杂的恒星，",
    "hypercomplexity stars).": "超复杂星）。",
    "If all power slots are full, to unequip a power and create a free slot you need to complexity.": "如果所有电源槽都已满，要取消装备电源并创建一个空闲槽，您需要复杂度。",
    "If it shows up for a longer time, that's probably a bug and you should use the buttons below.": "如果它显示的时间更长，那可能是一个错误，您应该使用下面的按钮。",
    "If it's an eternity how can you reach it in finite time?": "如果它是永恒的，你怎么能在有限的时间内达到它？",
    "If you think this ruins the game somehow, you can turn rewards off.": "如果您认为这会以某种方式破坏游戏，您可以关闭奖励。",
    "Imperial": "帝国",
    "Infinite": "无穷",
    "Larger checkboxes:": "较大的复选框：",
    "Last Ten Runs tab:": "最近十次运行选项卡：",
    "Lemme get some Dimbo- Boosts": "让我得到一些 Dimbo- Boosts",
    "List of hotkeys:": "热键列表：",
    "Log/second settings": "日志/秒设置",
    "Max all mode": "最大所有模式",
    "Need some help? Check the guide in the Options tab!": "需要一些帮助？检查选项选项卡中的指南！",
    "Next ℂC completion in header:": "标题中的下一个ℂC完成：",
    "No confirmation": "没有确认",
    "Normal generators and boosts": "普通发生器和助推器",
    "Off": "关闭",
    "On": "打开",
    "On (gradient)": "开（渐变）",
    "outside of Infinity Challenge": "无限挑战之外",
    "over": "超过",
    "peak ℂP/sec": "峰值ℂP/秒",
    "peak EP/sec": "峰值 EP/秒",
    "peak IP/sec": "峰值 IP/秒",
    "peak log ℂP/sec": "峰值日志ℂP/sec",
    "peak log EP/sec": "峰值对数 EP/秒",
    "peak log IP/sec": "峰值日志 IP/秒",
    "per": "每",
    "per boost this eternity above": "每提升这个永恒以上",
    "per second": "每秒",
    "per second.": "每秒。",
    "per tier).": "每层）。",
    "per-boost multiplier": "每升压乘数",
    "permanence": "永久性",
    "Permanence Autobuyer": "永久自动购买者",
    "Permanence can be spent on a variety of upgrades.": "永久性可以用于各种升级。",
    "permanence per eternity.": "永恒的永恒。",
    "Permanence:": "持久性：",
    "Seconds": "秒",
    "Shown": "显示",
    "Star Trek: The Next Generators": "星际迷航：下一代发生器",
    "theorem": "定理",
    "theorem purchases of a certain type, theorem costs of that type start increasing far more quickly.": "购买某种类型的定理，该类型的定理成本开始增长得更快。",
    "theorems (enough to buy all the studies), a fourth row will appear.": "定理（足以购买所有研究），将出现第四行。",
    "theorems in Complexity Challenge": "复杂性挑战中的定理",
    "theorems.": "定理。",
    "There are a lot of finality shard options. To hide most of them, go to the options tab and toggle (turn off) \"Full finality shard options\" in the \"other options\" part.": "有很多最终分片选项。要隐藏其中的大部分，请转到选项选项卡并在“其他选项”部分切换（关闭）“完全确定性分片选项”。",
    "There are a lot of finality shard options. To see the others, go to the options tab and toggle (turn on) \"Full finality shard options\" in the \"other options\" part.": "有很多最终分片选项。要查看其他选项，请转到选项选项卡并在“其他选项”部分切换（打开）“完全确定性分片选项”。",
    "There are a lot of power options. To hide most of them, go to the options tab and toggle (turn off) \"Full power options\" in the \"other options\" part.": "有很多电源选项。要隐藏其中的大部分，请转到选项选项卡并在“其他选项”部分中切换（关闭）“完全电源选项”。",
    "There are a lot of power options. To see the others, go to the options tab and toggle (turn on) \"Full power options\" in the \"other options\" part.": "有很多电源选项。要查看其他选项，请转到选项选项卡并在“其他选项”部分切换（打开）“全功率选项”。",
    "There are a lot of study options. To hide most of them, go to the options tab and toggle (turn off) \"Full study options\" in the \"other options\" part.": "有很多学习选择。要隐藏其中的大部分，请转到选项选项卡并在“其他选项”部分中切换（关闭）“完整学习选项”。",
    "There are a lot of study options. To see the others, go to the options tab and toggle (turn on) \"Full study options\" in the \"other options\" part.": "有很多学习选择。要查看其他选项，请转到选项选项卡并在“其他选项”部分切换（打开）“完整学习选项”。",
    "There are by default small rewards for completing achievements.": "默认情况下，完成成就会获得小额奖励。",
    "There are exponents on all normal generator multipliers based on infinity stars and on all infinity generator multipliers based on eternity stars (both less than": "所有基于无限星的正常生成器乘数和所有基于永恒星的无穷生成器乘数都有指数（均小于",
    "There are only 6": "只有6个",
    "There is also a small multiplier to the chroma cap based on total fourth-row study purchases (currently": "根据第四行研究的总购买量，色度上限也有一个小的乘数（目前",
    "There is no in-game reward for completing goals, but you win the game (and have finished it) when you complete them all.": "完成目标没有游戏内奖励，但是当您完成所有目标时，您就赢得了游戏（并且已经完成了游戏）。",
    "There's a multiplier on all": "有一个乘数",
    "There's a multiplier on Generator": "发生器上有一个乘数",
    "There's an exponent on the multipliers of all": "所有的乘数都有一个指数",
    "These aren't Ordinal Markup's infinite ordinals, but e.g. generator numbers, or more generally things which are the nth of something.": "这些不是 Ordinal Markup 的无限序数，而是例如生成器编号，或更一般地说，是某事物的第 n 个事物。",
    "These starting bonuses let you start finalities with more of various resources. Look below finality shard upgrades for more details.": "这些起始奖金可让您使用更多不同的资源开始终结。查看下面的最终分片升级以获取更多详细信息。",
    "This allows you to start with a Complexity Challenge": "这使您可以从复杂性挑战开始",
    "This base is used for calculating the value of the exponent, so if it's 16 and the display base is 10, 1e2 is 256.": "这个底数用于计算指数的值，所以如果它是 16 并且显示底数是 10，那么 1e2 就是 256。",
    "this complexity, multiplying all eternity generators by": "这种复杂性，将所有永恒生成器乘以",
    "this complexity.": "这种复杂性。",
    "this eternity, multiplying all": "这永恒，倍增所有",
    "this eternity.": "这个永恒。",
    "this finality.": "这个终局。",
    "Achievement descriptions at bottom of tab:": "标签底部的成就说明：",
    "Achievement notifications:": "成就通知：",
    "Achievement rewards:": "成就奖励：",
    "Achievements:": "成就：",
    "achievements.": "成就。",
    "Adding &a,b,c,d to the end of a study list will try to buy Study": "将 &a,b,c,d 添加到研究列表的末尾将尝试购买研究",
    "Additional multiplier to complexity generator powers:": "复杂性生成器功率的附加乘数：",
    "Additional multiplier to eternity generator powers:": "永恒发生器功率的附加乘数：",
    "Additional multiplier to infinity generator powers:": "无限发生器功率的附加乘数：",
    "Additional multiplier to normal generator powers:": "正常发生器功率的附加乘数：",
    "Adjust text colors too close to background:": "调整文本颜色太接近背景：",
    "After": "后",
    "After finality, EC tier auto-completion from complexities is": "最终确定后，EC 层从复杂性中自动完成是",
    "after next eternity reset.": "在下一次永恒重置之后。",
    "after unlocking galaxies.": "解锁星系后。",
    "After you get": "你得到后",
    "Alert on prediction:": "预测警报：",
    "All": "全部",
    "all apply.": "都适用。",
    "All but amount": "除了金额",
    "All eternity challenge rewards are disabled.": "所有永恒挑战奖励都被禁用。",
    "This game uses": "本游戏使用",
    "This is a serious warning about evil notation. Don't use it unless you want to not trust numbers.": "这是对邪恶符号的严重警告。除非您不想信任数字，否则不要使用它。",
    "This is used for autobuyer inputs.": "这用于自动购买者输入。",
    "This is used for Letters notation as the list of letters to use.": "这用于字母表示法作为要使用的字母列表。",
    "This is used for some small values that are best shown precisely": "这用于一些最能精确显示的小值",
    "This message can be disabled in the Options tab (\"Show export reminder after X seconds\").": "可以在“选项”选项卡中禁用此消息（“X 秒后显示导出提醒”）。",
    "This message is here in case you accidentally disabled something and forgot to enable it again.": "如果您不小心禁用了某些东西并忘记再次启用它，则会出现此消息。",
    "This option only affects the input for each autobuyer (AB). Also, it doesn't take into account notation (except for Hex); autobuyer inputs will generally still use Scientific.": "此选项仅影响每个自动购买者 (AB) 的输入。此外，它不考虑符号（十六进制除外）；自动购买者的输入通常仍会使用 Scientific。",
    "This option, rather than showing all the tabs at once, will divide the tabs intro groups and let you switch between viewing various groups, similarly to Antimatter Dimension's tab handling.": "此选项不是一次显示所有选项卡，而是划分选项卡介绍组，并让您在查看各个组之间切换，类似于 Antimatter Dimension 的选项卡处理。",
    "This setting controls what the M hotkey buys, and also what the Main tab \"Max all\" button buys.": "此设置控制 M 热键购买的内容，以及主选项卡“Max all”按钮购买的内容。",
    "This setting controls whether gain per second or log gain per second of things like IP is shown in various places. The default setting": "此设置控制是否在不同位置显示 IP 等事物的每秒增益或每秒对数增益。默认设置",
    "This text should never appear.": "此文本不应出现。",
    "Thus, all but the best": "因此，除了最好的",
    "Thus, you are automatically in whichever complexity challenges you have not yet violated the condition of this complexity.": "因此，您自动处于尚未违反此复杂性条件的任何复杂性挑战中。",
    "ticks may make it slow).": "蜱虫可能会使它变慢）。",
    "Ticks simulated so far:": "到目前为止模拟的刻度：",
    "time": "时间",
    "Time": "时间",
    "Time display:": "时间显示：",
    "Time past peak log/sec": "超过峰值日志/秒的时间",
    "Time past peak/sec": "过峰值时间/秒",
    "Time since gain was amount": "自收益为金额以来的时间",
    "Time since gain was total": "总收益以来的时间",
    "Time since possible": "可能的时间",
    "Time spent simulating ticks:": "模拟滴答声所花费的时间：",
    "Time to finish:": "完成时间：",
    "times (": "次（",
    "times each).": "每次）。",
    "You can only buy": "你只能买",
    "You can only have a single eternity challenge unlocked at a given time.": "您只能在给定时间解锁一个永恒挑战。",
    "You can press O to get a prediction from the Oracle on any tab.": "您可以按 O 在任何选项卡上从 Oracle 获取预测。",
    "You can toggle an autobuyer by pressing T + the corresponding hotkey.": "您可以通过按 T + 相应的热键来切换自动购买。",
    "You can't buy boosts and the per-boost multiplier is": "你不能购买提升，每次提升乘数是",
    "You can't buy boosts or more than one of each": "您不能购买任何提升或超过一个",
    "You can't buy boosts, the per-boost multiplier is": "你不能购买提升，每次提升的乘数是",
    "You can't buy boosts.": "你不能购买助推器。",
    "You can't buy Eternity Generator": "你买不到永恒发生器",
    "You can't buy or have studies.": "你不能买也不能学习。",
    "You can't prestige.": "你不能声望。",
    "You can't unlock chroma.": "您无法解锁色度。",
    "You can't unlock the Eternity Producer.": "您无法解锁 Eternity Producer。",
    "You cannot craft powers with negative rarity or powers with rarity greater than": "你不能制造具有负稀有度的力量或稀有度大于",
    "You do not need to complexity to complete complexity challenges.": "您不需要复杂性来完成复杂性挑战。",
    "You don't currently have any color presets.": "您目前没有任何颜色预设。",
    "You don't currently have any finality presets. You can create presets at the bottom of this tab.": "您目前没有任何确定性预设。您可以在此选项卡的底部创建预设。",
    "You don't currently have any power presets. You can create presets at the bottom of this tab.": "您目前没有任何电源预设。您可以在此选项卡的底部创建预设。",
    "You don't currently have any study presets. You can create presets at the bottom of this tab.": "您目前没有任何学习预设。您可以在此选项卡的底部创建预设。",
    "You don't currently have any tab presets.": "您目前没有任何选项卡预设。",
    "You gain a new power once every": "你每获得一次新的力量",
    "You gain your complexity points on complexity every second, without needing to complexity (ℂP generation).": "您每秒都会在复杂性上获得复杂性点，而无需复杂性（ℂP 生成）。",
    "You gain your infinity points on infinity every second, without needing to infinity (IP generation)": "您每秒获得无限点数，而无需无限（IP 生成）",
    "You get": "你得到",
    "You have a": "你有一个",
    "You have been in": "你已经在",
    "You have completed": "您已完成",
    "You have made": "你做了",
    "You have not exported your save for a long time. You might want to export regularly.": "您已经很久没有导出存档了。您可能希望定期导出。",
    "You have produced": "你制作了",
    "You have spent": "你已经花了",
    "You have unlocked": "你已解锁",
    "You have won the game! Congratulations!": "你赢了比赛！恭喜！",
    "You keep your theorems, studies, and best boost power on complexity.": "您保留您的定理、研究和对复杂性的最佳增强能力。",
    "You need": "你需要",
    "You need to buy at least one eternity generator before you can buy theorems with eternity points.": "您需要至少购买一台永恒生成器，然后才能购买具有永恒点的定理。",
    "You need to complete all the normal challenges to be able to break infinity.": "您需要完成所有正常挑战才能打破无限。",
    "You need to eternity before you can buy theorems with anything.": "你需要永恒，然后才能用任何东西购买定理。",
    "You start each": "你开始每个",
    "You start with": "你从",
    "You will get": "你会得到",
    "You will start generating boost power for each boost this eternity above": "您将开始为上述永恒的每个提升产生提升功率",
    "You would gain a new power once every": "您将获得一次新的力量",
    "Your": "您的",
    "Your achievements": "你的成就",
    "Your fastest complexity took": "你最快的复杂性花了",
    "Your fastest eternity took": "你最快的永恒",
    "Your fastest finality took": "你最快的结局了",
    "Your fastest infinity took": "你最快的无限",
    "Your galaxies are increasing the strength of new powers by": "你们的星系正在通过以下方式增强新力量的力量",
    "Your highest number of boosts this eternity is": "你这个永恒的最高提升次数是",
    "Your stellar product is": "你的明星产品是",
    "collapsed due to an excess of stars.": "由于恒星过多而坍塌。",
    "Color change:": "颜色变化：",
    "Color presets (": "颜色预设（",
    "color presets. Delete existing presets to create more.": "颜色预设。删除现有预设以创建更多预设。",
    "Color scheme:": "配色方案：",
    "Complete": "完全的",
    "Complete a complexity achievement.": "完成一项复杂性成就。",
    "Complete a normal challenge.": "完成一次普通挑战。",
    "Complete all eternity challenges (": "完成所有永恒挑战（",
    "Complete all eternity challenges, without using automatic eternity challenge completion, in Complexity Challenge": "在复杂性挑战中完成所有永恒挑战，而不使用自动永恒挑战完成",
    "Complete all eternity milestones.": "完成所有永恒里程碑。",
    "Complete all finality milestones.": "完成所有确定性里程碑。",
    "Complete all infinity challenges.": "完成所有无限挑战。",
    "Complete all the complexity achievements.": "完成所有复杂的成就。",
    "Complete an eternity challenge.": "完成一个永恒挑战。",
    "Complete an infinity challenge.": "完成一个无限挑战。",
    "Complete Complexity Challenge": "完成复杂性挑战",
    "Completing all complexity achievements for the first time will also let you view the Powers tab.": "首次完成所有复杂性成就还将让您查看“权力”选项卡。",
    "Completing all eternity milestones for the first time will also let you view the Eternity Producer tab.": "首次完成所有永恒里程碑还可以让您查看永恒生产者选项卡。",
    "Completion colors:": "完成颜色：",
    "Completion gradients:": "完成梯度：",
    "completion.": "完成。",
    "complexit": "复杂性",
    "complexities.": "复杂性。",
    "Complexity achievement notifications:": "复杂性成就通知：",
    "Complexity Achievements:": "复杂性成就：",
    "Complexity Challenges:": "复杂性挑战：",
    "Complexity reset:": "复杂度重置：",
    "Confirmation": "确认",
    "Confirmations:": "确认：",
    "ℂP without unlocking red.": "ℂP 不解锁红色。",
    "ℂP, giving": "ℂP，给予",
    "Create a color preset": "创建颜色预设",
    "Create a tab preset": "创建选项卡预设",
    "Current challenges in header:": "标题中的当前挑战：",
    "Decrease page size if page is too narrow:": "如果页面太窄，减小页面大小：",
    "Disabled": "已禁用",
    "Discord": "不和谐",
    "Display base": "展示底座",
    "Dots": "点",
    "Dull yellow (": "暗黄（",
    "Emoji": "表情符号",
    "Engineering": "工程",
    "Eternity challenge respec:": "永恒挑战：",
    "Eternity Challenges:": "永恒挑战：",
    "Eternity Milestones:": "永恒里程碑：",
    "Eternity Producer:": "永恒制作人：",
    "Evil": "邪恶的",
    "Exponent base": "指数底",
    "Export color scheme": "导出配色方案",
    "Export tabs to show": "导出选项卡以显示",
    "Exported save (also copied to clipboard):": "导出的保存（也复制到剪贴板）：",
    "Exported tabs to show (also copied to clipboard):": "要显示的导出选项卡（也复制到剪贴板）：",
    "Finality Milestones:": "最终里程碑：",
    "Finality shard upgrades respec:": "最终分片升级方面：",
    "Finality Shards:": "最终分片：",
    "Format ordinals": "格式序数",
    "fraction of chroma cap": "色度上限分数",
    "Fraction of peak log/sec": "峰值对数/秒的分数",
    "Fraction of peak/sec": "峰值/秒的分数",
    "Full finality shard options:": "完整的最终分片选项：",
    "Full power options:": "全功率选项：",
    "Full study options:": "完整的学习选择：",
    "Gain permanence.": "获得永久性。",
    "Gaining permanence:": "获得永久性：",
    "galax": "银河",
    "Galaxies": "星系",
    "Galaxies to make dilated next complexity reset:": "星系使扩张的下一个复杂性重置：",
    "Galaxies:": "星系：",
    "Galaxy effect (0 means cap)": "银河效应（0 表示上限）",
    "game tick": "游戏滴答声",
    "game ticks (more than": "游戏滴答声（超过",
    "Generator": "发生器",
    "Generator 9 jokes don't ex... oh wait": "发生器 9 的笑话不前...哦等等",
    "generators": "发生器",
    "Generators and upgrades in current tab": "当前选项卡中的生成器和升级",
    "Get": "得到",
    "Get a per-boost multiplier of": "获得每次提升的乘数",
    "Get a power with rarity at least": "至少获得稀有的力量",
    "Get at least": "至少得到",
    "Get finality shard upgrade starting bonuses to a strength of": "获得最终碎片升级起始奖金，强度为",
    "Get prediction": "获取预测",
    "Github repository (also has other stuff)": "Github 存储库（还有其他东西）",
    "Given a multiplier x, let y be log(x,": "给定一个乘数 x，设 y 为 log(x,",
    "Goals": "目标",
    "Goals:": "目标：",
    "goals.": "目标。",
    "FE000000 lore when?": "FE000000 什么时候绝杀？",
    "): Break infinity.": "): 打破无限。",
    "): Buy a study.": "）：购买研究。",
    "): Buy Generator": "): 购买发生器",
    "): Buy the maximum possible of all finality shard upgrades.": ")：购买所有最终分片升级中的最大可能。",
    "): Complete": "）： 完全的",
    "): Complete a complexity achievement.": ")：完成一项复杂性成就。",
    "): Complete a normal challenge.": ")：完成一次普通挑战。",
    "): Complete all eternity challenges (": "): 完成所有永恒挑战 (",
    "): Complete all eternity milestones.": ")：完成所有永恒里程碑。",
    "): Complete all finality milestones.": ")：完成所有确定性里程碑。",
    "): Complete all infinity challenges.": ")：完成所有无限挑战。",
    "): Complete all the complexity achievements.": ")：完成所有复杂度成就。",
    "): Complete an eternity challenge.": ")：完成永恒挑战。",
    "): Complete an infinity challenge.": ")：完成一个无限挑战。",
    "): Complexity for": "): 复杂度",
    "): Complexity in": "): 复杂性",
    "): Complexity while in all": "): 复杂性",
    "): Complexity.": ")：复杂性。",
    "): Craft a power.": "): 制造力量。",
    "): Eternity for": "): 永恒",
    "): Eternity in": "): 永恒在",
    "): Eternity.": "）： 永恒。",
    "): Finality in": "): 终局性",
    "): Finality.": "）：确定性。",
    "): Gain permanence.": "): 获得持久性。",
    "): Get": "）： 得到",
    "): Get a power with rarity at least": "): 至少获得稀有的力量",
    "): Get at least": "): 至少得到",
    "): Get finality shard upgrade starting bonuses to a strength of": "): 获得最终碎片升级起始奖金，强度为",
    "): Have": "）： 有",
    "): Have all": "): 拥有所有",
    "): Have all the first-row studies at once.": ")：一次完成所有第一行研究。",
    "): Have all the studies in the first three rows at once.": ")：一次完成前三行的所有研究。",
    "): Have at least": "): 至少有",
    "): Have autobuyers for all": "): 为所有人提供自动购买者",
    "): Have some generator multiplier over": "): 有一些生成器乘数",
    "): Have the eternity power extra multiplier reach its cap (which is": ")：让永恒之力额外乘数达到其上限（即",
    "): Have the time for the galaxy effect to cap be at least": "): 至少有时间让星系效应达到上限",
    "): Infinity in Infinity Challenge": "): 无限挑战中的无限",
    "): Infinity in Normal Challenge": "): 正常挑战中的无限",
    "): Infinity.": "）： 无穷。",
    "): Prestige.": "）： 声望。",
    "): Sacrifice.": "）： 牺牲。",
    "): Unlock chroma.": ")：解锁色度。",
    "): Unlock galaxies.": ")：解锁星系。",
    "): Unlock powers.": ")：解锁权力。",
    "): Unlock the Eternity Producer.": ")：解锁永恒生产者。",
    "): Unlock the Oracle.": "): 解锁神谕。",
    "). x is reduced to": "）。 x 减少到",
    "+ finalities) is a multiple of": "+ finalities) 是的倍数",
    "+ finalities), doubled if (": "+ finalities), 加倍 if (",
    ",\n          strength": ",\n 强度",
    ", and": "， 和",
    ", and rarity": ", 稀有度",
    ", and will produce": ", 并且会产生",
    ", and you can view the Chroma tab": "，您可以查看色度选项卡",
    ", and you can't prestige. You can sacrifice multiple times at the same point and the sacrifice bonuses multiply, but sacrifice resets everything that prestige resets.": "，你不能声望。你可以在同一点牺牲多次，牺牲加成会成倍增加，但牺牲会重置所有声望重置。",
    ", based on eternity points).": "，基于永恒点）。",
    ", both under an MIT license.": "，两者都在 MIT 许可下。",
    ", but all": ", 但所有",
    ", but sacrifice is far stronger.": "，但牺牲要强大得多。",
    ", but the multiplier per boost is squared.": "，但每次提升的乘数是平方的。",
    ", but you haven't unlocked them yet.": "，但您尚未解锁它们。",
    ", capping in": ", 封顶",
    ", from \"On the other side\")": ", 来自\"另一边\")",
    ", giving you": "，给你",
    ", giving you starting bonuses with a strength of": ", 给你起始奖金，强度为",
    ", multiplying all": ", 乘以所有",
    ", multiplying all complexity generators (ℂGs) by": "，将所有复杂度生成器 (ℂGs) 乘以",
    ", multiplying all eternity generators (EGs) by": "，将所有永恒生成器 (EG) 乘以",
    ", multiplying all finality generators (FGs) by": "，将所有确定性生成器 (FG) 乘以",
    ", multiplying all infinity generators (IGs) by": "，将所有无限生成器 (IG) 乘以",
    ", multiplying all infinity generators by": "，将所有无限生成器乘以",
    ", next at": "，接下来在",
    ", next at 1.000 EP": ", 接下来是 1.000 EP",
    ", next at 1.000 IP": ", 接下来是 1.000 IP",
    ", next at 1.000 stars": "，接下来是 1.000 颗星",
    ", next in": ", 下一个",
    ", Next:": "， 下一个：",
    ", Next: ^": ", 下一个: ^",
    ", Next: +": ", 下一个: +",
    ", Next: Cost ^": ", 下一个：成本 ^",
    ", slow above": ", 上面慢",
    ", starting at": "， 开始于",
    ", the amounts of all lower": "，所有较低的金额",
    ", very slow above": ", 上面很慢",
    ". (Generator": ". （发生器",
    ". All other": ".所有其他",
    ". Due to the Eternity Producer, they multiply all eternity generators by": ".由于永恒生产者，他们将所有永恒生成器乘以",
    ". Every time you buy a generator or boost, or sacrifice or prestige, this exponent resets to": ".每次您购买发生器或助推器，或牺牲或声望时，该指数都会重置为",
    ". Every time you buy a generator or boost, or sacrifice or prestige, this multiplier resets to": ".每次您购买发生器或助推器，或牺牲或声望时，此乘数都会重置为",
    ". Every time you prestige, this multiplier resets to": ".每次你获得声望时，这个乘数都会重置为",
    ". If you infinity more, you will automatically exit this challenge.": ".如果您无限多，您将自动退出此挑战。",
    "'Will there be new content?' -everyone at some point (answer: no)": "“会有新的内容吗？” -每个人都在某个时候（答案：不）",
    "(\"Broke every stone\" disables this.)": "（“打破每一块石头”禁用此功能。）",
    "(a breakdown is below the theorem purchase buttons) and": "（细分在定理购买按钮下方）和",
    "(actually one EC tier per": "（实际上每个 EC 层",
    "(allowing you to enter": "（允许您输入",
    "(apart from Generator": "（除了发生器",
    "(as usual) and ^": "（像往常一样）和^",
    "(based on eternities this complexity)": "（基于永恒这种复杂性）",
    "(based on eternities)": "（基于永恒）",
    "(based on eternities).": "（基于永恒）。",
    "(based on Eternity Generator": "（基于永恒生成器",
    "(based on total EP this complexity)": "（基于总 EP 这种复杂性）",
    "(bought theorems) +": "（购买定理）+",
    "(capped)": "（封顶）",
    "(disabled because you can complexity)": "（禁用，因为你可以复杂）",
    "(Disabling this doesn't put you in this challenge yet, since this challenge is locked.)": "（禁用此功能不会让您进入此挑战，因为此挑战已锁定。）",
    "(Due to \"On the other side\", you also need to respec studies to enter this challenge. Disabling buying studies will respec studies on complexity.)": "（由于“在另一边”，您还需要重新指定研究才能进入此挑战。禁用购买研究将重新指定复杂性研究。）",
    "(extra theorems) =": "（额外定理）=",
    "(for example,": "（例如，",
    "(from EP) =": "（来自 EP）=",
    "(from finality shard upgrade bonuses)": "（来自终结性碎片升级奖金）",
    "(from IP) +": "（来自 IP）+",
    "(from stars) +": "（来自星星）+",
    "(from stellar product) +": "（来自明星产品）+",
    "(from total ℂP this finality)": "（来自总ℂP这个最终性）",
    "(giving": "（给",
    "(including Generator": "（包括发生器",
    "(increased to +": "（增加到 +",
    "(IP).": "（知识产权）。",
    "(lower-bounded by": "（下界为",
    "(maxed)": "（最大化）",
    "(no auto-completions this complexity)": "（没有自动完成这种复杂性）",
    "(of any type)": "（任何类型）",
    "(reversed when holding shift)": "（保持换档时反转）",
    "(since you haven't unlocked galaxies yet)": "（因为你还没有解锁星系）",
    "(slow)": "（减缓）",
    "(Starting complexity achievements are given top-to-bottom, and left-to-right within each row.)": "（起始复杂度成就在每行中从上到下和从左到右给出。）",
    "(such as Normal Challenge": "（如普通挑战",
    "(the maximum rarity of generated powers).": "（产生的力量的最大稀有度）。",
    "(This gain of finality shards is": "（最终分片的收益是",
    "(triggering every": "（触发每个",
    "(will be automatically deleted due to being bad enough to be useless)": "（会因为坏到没用会被自动删除）",
    "(You can get this with bought theorems from previous complexities; only buying theorems in your current complexity stops you from getting it.)": "（你可以通过从以前的复杂性中购买定理来获得这个；只有在你当前的复杂性中购买定理才能阻止你得到它。）",
    "(you don't have to wait for the galaxy effect to actually reach the cap).": "（您不必等待星系效应真正达到上限）。",
    ") and boosts throughout this challenge. Each Generator": ") 并在整个挑战中得到提升。每台发生器",
    ") are multiplied by your amount of Generator": ") 乘以您的发生器数量",
    "1-8 to buy max of Generator 1-8 respectively, shift+1-8 to buy one of Generator 1-8 respectively, G to max all generators, M to max all generators and boosts, A to turn all autobuyers on/off, and shift+A to toggle all autobuyers": "1-8 分别购买发生器 1-8 的最大值，shift+1-8 分别购买发生器 1-8 中的一个，G 最大化所有发生器，M 最大化所有发生器和助推器，A 开启/关闭所有自动购买 , 和 shift+A 切换所有自动购买者",
    "1: stars float in space, 2: cover yourself in stars, 3: wait for it to space, 4: fly": "1：星星漂浮在太空中，2：用星星遮住自己，3：等待它进入太空，4：飞翔",
    "b total times, and so on.\n          If the game cannot buy a study in the list as many times as asked for, it will move to the next study.\n          Adding &sa,b,c,d, where the s is a literal s, will instead try to spend theorems on fourth-row studies in proportion to their costs when bought a, b, c, and d times.\n          This &sa,b,c,d syntax allows for a preset to keep the same relative values between fourth-row studies (that is, which is more important and which is less) without the preset changing for every fourth-row study purchase.": "b 总次数，依此类推。\n 如果游戏无法按照要求购买列表中的一项研究，它将移至下一项研究。\n 添加 &sa,b,c,d，其中 s 是 当购买 a、b、c 和 d 次时，文字 s 将尝试按照与成本成比例的比例将定理花费在第四行研究上。\n 这种 &sa,b,c,d 语法允许预设保持 第四行研究之间的相对值相同（即哪个更重要，哪个更小），而无需为每个第四行研究购买更改预设。",
    "boost": "促进",
    "Boost Autobuyer": "提升自动购买者",
    "Boost costs are massively increased.": "提升成本大幅增加。",
    "boost power in Complexity Challenge": "在复杂性挑战中提升力量",
    "boost power per second (": "每秒提升功率（",
    "boost power, increasing the per-boost multiplier by": "升压功率，增加每升压乘数",
    "boosts in Eternity Challenge": "永恒挑战中的提升",
    "boosts.": "提振。",
    "Both": "两个都",
    "Bought theorems:": "购买定理：",
    "Brackets": "括号",
    "Break infinity.": "打破无限。",
    "break_infinity": "break_infinity",
    "Breaking infinity for the first time will also let you view the Infinity Challenges tab.": "首次打破无限也将让您查看无限挑战选项卡。",
    "Brown": "棕色的",
    "but gain": "但获得",
    "Button colors:": "按钮颜色：",
    "Buy a study.": "买书房。",
    "Buy a theorem with eternity points": "购买具有永恒点的定理",
    "Buy a theorem with infinity points": "购买具有无穷大点的定理",
    "Buy a theorem with stars": "购买带有星星的定理",
    "Buy Generator": "购买发生器",
    "Buy max": "买最大",
    "Buy max theorems with eternity points": "用永恒点购买最大定理",
    "Buy max theorems with infinity points": "购买具有无穷大点的最大定理",
    "Buy max theorems with stars": "用星星购买最大定理",
    "Buy singles": "买单个",
    "Buy the maximum possible of all finality shard upgrades.": "尽可能购买所有最终分片升级。",
    "Buying a study will increase the costs of all studies on other rows by": "购买一项研究将使其他行的所有研究的成本增加",
    "Buying boosts:": "购买提升：",
    "Buying Eternity Generator": "购买永恒发生器",
    "Buying studies:": "购买研究：",
    "by": "经过",
    "By default, only goals up to the next goal after the last completed goal are displayed.": "默认情况下，仅显示最后一个完成目标之后直到下一个目标的目标。",
    "by its amount.": "以其数量。",
    "by their amount^": "按他们的数量^",
    "can be bought up to": "最多可以买",
    "can be equipped at once.": "可以一次性装备。",
    "can be equipped at the same time.": "可以同时装备。",
    "Change the values of colors:": "更改颜色的值：",
    "Change to current color scheme": "更改为当前配色方案",
    "Change to current equipped powers": "更改为当前装备的力量",
    "Change to current studies": "更改当前研究",
    "Change to current upgrades": "更改为当前升级",
    "Change to currently shown tabs": "更改为当前显示的选项卡",
    "checks whether your relevant autobuyer is set to a mode that uses log/second.": "检查您的相关自动购买是否设置为使用日志/秒的模式。",
    "chroma": "色度",
    "Chroma": "色度",
    "chroma (capped at": "色度（上限为",
    "Chroma always produces all unlocked colors at once.": "Chroma 总是同时产生所有未锁定的颜色。",
    "Chroma amount": "色度量",
    "Chroma as fraction of cap": "色度作为上限的分数",
    "Chroma buildup speed": "色度累积速度",
    "Chroma gain will slow down over time, gradually approaching its cap but taking a very long time to reach it.": "色度增益会随着时间的推移而减慢，逐渐接近其上限，但需要很长时间才能达到。",
    "Chroma:": "色度：",
    "Click on the name of a color preset on the line below to use that color scheme:": "单击下面一行颜色预设的名称以使用该配色方案：",
    "Click on the name of a finality preset on the line below to buy those finality shard upgrades:": "单击下面一行中的确定性预设的名称以购买这些确定性碎片升级：",
    "Click on the name of a power preset on the line below to equip those powers:": "单击下面一行中的电源预设名称以装备这些电源：",
    "Click on the name of a study preset on the line below to load that study list:": "单击以下行上的研究预设的名称以加载该研究列表：",
    "Click on the name of a tab preset on the line below to show those tabs:": "单击下面一行中的选项卡预设名称以显示这些选项卡：",
    "Clicked button outlines:": "单击的按钮轮廓：",
    "Clock": "钟",
    "Completions": "完成",
    "Dark": "深色",
    "Much of this game was based on Antimatter Dimensions, which you should play (though it is a bit slower-paced).": "这个游戏的大部分内容都是基于反物质维度，你应该玩（虽然它的节奏有点慢）。",
    "You can disable those messages in options. But I guess you know that, since you enabled them.": "您可以在选项中禁用这些消息。但我想你知道，因为你启用了它们。",
    "You can report bugs on the game's Github repo or by joining the game's Discord server, both linked in Options.": "您可以在游戏的 Github 存储库或加入游戏的 Discord 服务器上报告错误，两者都在选项中链接。",
    "All generators and upgrades": "所有发生器和升级",
    "All generators, upgrades, and unlocks": "所有生成器、升级和解锁",
    "All sources of chroma buildup speed act retroactively in the current eternity.": "所有色度累积速度的来源都会在当前的永恒中追溯作用。",
    "Alphabet": "字母",
    "Always have EP generation.": "始终有 EP 生成。",
    "Amount": "数量",
    "amount on finality:": "最终金额：",
    "amount)": "数量）",
    "and": "和",
    "and boosts throughout this challenge. This count does not reset on prestige.": "并在整个挑战中得到提升。此计数不会因声望而重置。",
    "and boosts.": "和提升。",
    "and can use between": "并且可以在之间使用",
    "and doubling every": "并且每翻一番",
    "and gave": "并给了",
    "and Generator": "和发生器",
    "and multiplying": "和相乘",
    "and raising all normal and infinity generator multipliers ^": "并提高所有正常和无穷大的生成器乘数^",
    "and Study": "和学习",
    "and they're now fully complete": "他们现在已经完全完成了",
    "Antimatter Dimensions Notations": "反物质维度符号",
    "are reset, like a sacrifice without the benefit.": "被重置，就像没有利益的牺牲一样。",
    "as soon as you unlock": "只要你解锁",
    "Ask the Oracle to look": "请 Oracle 看看",
    "At": "在",
    "At most": "最多",
    "Auto buy theorems with eternity points:": "具有永恒点的自动购买定理：",
    "Auto buy theorems with infinity points:": "具有无穷大点的自动购买定理：",
    "Auto buy theorems with stars:": "带星号的自动购买定理：",
    "Auto-completed EC tiers can be stored up by turning auto-EC completion off.": "可以通过关闭自动 EC 完成来存储自动完成的 EC 层。",
    "auto-completing an EC tier every": "每次自动完成一个 EC 层",
    "Auto-EC completion:": "自动 EC 完成：",
    "Auto-load:": "自动加载：",
    "Auto:": "自动：",
    "autobuyer": "自动购买者",
    "Autobuyer": "自动购买者",
    "Autobuyer (triggering every game tick)": "Autobuyer（触发每个游戏滴答声）",
    "Autobuyer digits of precision": "Autobuyer 精确度数",
    "autobuyer, and an eternity autobuyer.": "自动购买者和永恒的自动购买者。",
    "autobuyer.": "自动购买者。",
    "Autobuyers": "自动购买者",
    "Autobuyers options on this tab only apply to autobuyers on this tab.": "此选项卡上的自动购买者选项仅适用于此选项卡上的自动购买者。",
    "Autobuyers:": "自动购买者：",
    "Automatically complete": "自动完成",
    "Automatically gain permanence every second without needing to reset eternities.": "每秒自动获得永久性，无需重置永恒。",
    "Automatically swap equipped powers with better stored powers of the same type.": "自动将装备的力量与相同类型的更好的储存力量交换。",
    "Automatically turn all autobuyers off when entering normal challenges:": "进入正常挑战时自动关闭所有自动购买：",
    "Automatically unlock powers when possible.": "尽可能自动解锁权力。",
    "Automatically unlock the Eternity Producer, chroma, and colors of chroma when possible.": "尽可能自动解锁 Eternity Producer、色度和色度颜色。",
    "Automatically unlock the Oracle and galaxies when possible.": "尽可能自动解锁神谕和星系。",
    "Background:": "背景：",
    "Bar": "条",
    "base production per second)": "每秒基础产量）",
    "based on prestige power (": "基于声望的权力（",
    "based on stars, capping at": "基于星星，上限为",
    "based on your finalities (currently up to": "根据您的最终结果（目前最多",
    "Being in a complexity challenge doesn't prevent you from violating its condition.": "处于复杂性挑战中并不能阻止您违反其条件。",
    "beyond the last achievement you have are shown. The others are replaced with question marks.": "超出您的最后一个成就显示。其他的被问号代替。",
    "Black": "黑色",
    "Blind": "盲人",
    "Blue": "蓝色",
    "generator": "发生器",
    "Halfway": "一半",
    "Locked": "未解锁",
    "Not reached": "未达到",
    "This power of two doesn't exist": "2的幂并不存在",
    "Unlocked": "已解锁",
    "are": "是",
    "5G network": "5G 网络",
    "best boost power this complexity": "最好能增强这种复杂性",
    "can i just say that I'm against news tickers": "我能说我反对新闻行情吗",
    "Click this for a nonexistent secret achievement.": "单击此按钮可获得不存在的秘密成就。",
    "Easy": "简单",
    "Exported save!": "存档已导出！",
    "Imagine if these things scrolled across the screen. Then presumably they could be way longer.": "想象一下，如果这些东西在屏幕上滚动。 然后大概他们可能会更长。",
    "Manually saved!": "手动保存！",
    "This game was named after a large number (2.004e19728) in Hex notation, which shows up at certain points in the game.": "该游戏以十六进制表示法中的一个大数字 (2.004e19728) 命名，该数字出现在游戏的某些点上。",
    "Complete all complexity achievements.": "完成所有复杂性成就。",
    "would be": "将会",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Achievement unlocked: ": "成就解锁:",
    "at least one of Generator ": "至少1个生成器 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " stars? Those are rookie numbers, pump those numbers up!": " 星星？ 这些是新秀数字，把这些数字抽起来！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) second$/, '$1 秒'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) stars$/, '$1e$2 星星'],
    [/^([\d\.]+)e([\d\.,]+) seconds$/, '$1e$2 秒'],
    [/^([\d\.]+)e([\d\.,]+) total eternity points$/, '$1e$2 总永恒点数'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);