/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Reward:": "报酬：",
    "Reward: All other eternity challenge rewards are stronger.": "奖励：所有其他永恒挑战奖励更强。",
    "Reward: Boosts are cheaper.": "奖励：提升更便宜。",
    "Reward: Exponent to Infinity Generator": "奖励：无限生成器 的指数",
    "Reward: Exponent to infinity generator multipliers.": "奖励：无限生成器乘数的指数。",
    "Reward: Exponent to prestige power based on infinity stars (": "奖励：基于无限星的声望力量指数（",
    "Reward: Exponent to prestige power.": "奖励：声望力量的指数。",
    "Reward: Extra theorems.": "奖励：额外的定理。",
    "Reward: Faster Boost Autobuyer (triggering every game tick)": "奖励：更快的提升自动购买者（触发每个游戏滴答声）",
    "Reward: Faster Generator": "奖励：更快的发生器",
    "Reward: Infinity Autobuyer": "奖励：无限自动购买者",
    "Reward: Multiplier to all infinity generators based on time in infinity (": "奖励：基于无限时间的所有无限发生器的乘数（",
    "Reward: Multiplier to chroma cap.": "奖励：色度上限的乘数。",
    "Reward: Multiplier to eternity gain.": "奖励：永久收益的乘数。",
    "Reward: Multiplier to eternity generators.": "奖励：永恒生成器的乘数。",
    "Reward: Multiplier to Infinity Generator": "奖励：无限生成器的乘数",
    "Reward: Multiplier to infinity generators based on eternity points produced this complexity.": "奖励：基于永恒点的无限生成器的乘数产生了这种复杂性。",
    "Reward: Multiplier to infinity generators based on total infinity points produced this eternity.": "奖励：基于总无限点的无限生成器的乘数产生了这个永恒。",
    "Reward: Multiplier to normal generators based on stars.": "奖励：基于星星的普通生成器的乘数。",
    "Reward: Multiplier to per-purchase Eternity Generator": "奖励：每次购买的乘数永恒生成器",
    "Reward: Prestige Autobuyer": "奖励：声望自动购买者",
    "Reward: Sacrifice Autobuyer": "奖励：牺牲自动购买者",
    "Reward: Sacrifice is stronger.": "奖励：牺牲更强。",
    "Reward: The multiplier to generators based on total IP this eternity is uncapped.": "奖励：基于此永恒总 IP 的生成器乘数没有上限。",
    "Sacrifice Autobuyer": "牺牲自动购买者",
    "sacrifice multiplier multiplying Generator": "牺牲乘数乘法生成器",
    "Sacrifice no longer resets anything.": "牺牲不再重置任何东西。",
    "Sacrifice:": "牺牲：",
    "Sacrifice.": "牺牲。",
    "Unequip": "取消装备",
    "Unequip equipped powers and": "取消装备 已装备的力量和",
    "Unequip equipped powers on next complexity:": "取消装备 已装备的力量在下一个复杂性：",
    "Unequip equipped powers when loading a preset:": "加载预设时取消装备的力量：",
    "Unlock": "解锁",
    "Unlock a finality autobuyer.": "解锁最终自动购买者。",
    "Unlock a new color of chroma.": "解锁一种新的色度。",
    "Unlock an Infinity Generator": "解锁无限发生器",
    "Unlock autobuyers for power shard upgrades.": "解锁自动购买者以进行电源碎片升级。",
    "Unlock autobuyers for repeatable infinity upgrades.": "解锁自动购买者以进行可重复的无限升级。",
    "Unlock Chroma": "解锁色度",
    "Unlock chroma in Complexity Challenge": "在复杂性挑战中解锁色度",
    "Unlock chroma.": "解锁色度。",
    "Unlock equipped powers auto-load.": "解锁装备的力量自动加载。",
    "Unlock Galaxies": "解锁星系",
    "Unlock galaxies.": "解锁星系。",
    "Unlock Powers": "解锁权力",
    "Unlock powers.": "解锁权力。",
    "Unlock Slow Boost Autobuyer": "解锁慢速自动购买",
    "Unlock Slow Generator": "解锁慢速发生器",
    "Unlock study list auto-load.": "解锁学习列表自动加载。",
    "Unlock the Eternity Producer": "解锁永恒制作人",
    "Unlock the Eternity Producer.": "解锁永恒生产者。",
    "Unlock the Oracle": "解锁甲骨文",
    "Unlock the Oracle.": "解锁神谕。",
    "Unlocking chroma and colors:": "解锁色度和颜色：",
    "Unlocking galaxies will also give you autobuyers for complexity generators and power upgrades.": "解锁星系还将为您提供复杂性发生器和电力升级的自动购买者。",
    "Unlocking powers for the first time will also let you view the Oracle tab.": "首次解锁权力还可以让您查看 Oracle 选项卡。",
    "Unlocking powers will also let you gain your eternity points on eternity every second, without needing to eternity (EP generation).": "解锁能力还将让您每秒获得永恒点数，而无需永恒（EP 生成）。",
    "Unlocking the Eternity Producer for the first time will also let you view the Eternity Challenges tab.": "首次解锁 Eternity Producer 还会让您查看 Eternity Challenges 选项卡。",
    "Unlocking the Eternity Producer:": "解锁永恒生产者：",
    "Unlocking the Oracle for the first time will also let you view the Galaxies tab.": "首次解锁 Oracle 还可以查看 Galaxies 选项卡。",
    "unspent finality shard": "未使用的最终分片",
    "unspent theorem": "未使用定理",
    "up to a total times, then Study": "最多总次数，然后学习",
    "used for Complexity Challenge": "用于复杂性挑战",
    "View all": "查看全部",
    "View all complexity generators even if they would be otherwise invisible:": "查看所有复杂性生成器，即使它们本来是不可见的：",
    "View all eternity generators even if they would be otherwise invisible:": "查看所有永恒生成器，即使它们本来是不可见的：",
    "View all finality generators even if they would be otherwise invisible:": "查看所有最终生成器，即使它们本来是不可见的：",
    "View all infinity generators even if they would be otherwise invisible:": "查看所有无穷大生成器，即使它们本来是不可见的：",
    "View stars and generators anyway:": "无论如何查看星星和发生器：",
    "were equipped.": "配备。",
    "when entering infinity challenges:": "进入无限挑战时：",
    "When it's turned on again you'll get all the new auto-completed EC tiers at once.": "当它再次打开时，您将立即获得所有新的自动完成的 EC 层。",
    "will be dilated, making the galaxy effect have speed": "会膨胀，让星系效应有速度",
    "will trigger in": "将触发",
    "with": "和",
    "with all eternity challenges completed.": "完成所有永恒的挑战。",
    "with all normal challenges completed. (You also keep autobuyers and infinity remains broken.)": "完成所有正常挑战。 （您还保留了自动购买者，并且无穷大仍然被破坏。）",
    "with EP equal to your highest-ever number of boosts (": "EP 等于你有史以来最高的提升次数（",
    "with eternities based on your complexities (currently": "基于你的复杂性的永恒（目前",
    "with infinities based on your eternities (currently": "无限基于你的永恒（目前",
    "with infinity points based on your eternities (currently": "无限点基于你的永恒（目前",
    "with stars based on your eternities (currently": "与基于你永恒的星星（目前",
    "with time in complexity based on your finalities (currently": "根据您的最终结果（目前",
    "without sacrificing.": "不牺牲。",
    "Cost:": "成本：",
    "counts both those equipped and stored, but powers are never deleted while equipped.": "装备和储存的都计算在内，但装备时永远不会删除权力。",
    "Craft a power with type": "用类型制造力量",
    "Craft a power.": "制造力量。",
    "Crafted power": "精雕细琢的力量",
    "Crafting cost depends only on rarity (not on type), and is always at least twice the power shards gained from deletion.": "制作成本仅取决于稀有度（与类型无关），并且始终至少是从删除中获得的能量碎片的两倍。",
    "Create a finality preset": "创建最终性预设",
    "Create a power preset": "创建电源预设",
    "Create a preset": "创建预设",
    "Current effects of equipped powers:": "装备力量的当前效果：",
    "Current:": "当前的：",
    "Current: ^": "当前：^",
    "Current: +": "当前：+",
    "Current: Cost ^": "当前：成本 ^",
    "Currently all the syntax is visible.": "目前所有语法都是可见的。",
    "Currently:": "目前：",
    "Delete": "删除",
    "Delete (+": "删除 (+",
    "Despite this, the total cost of studies does not depend on the order you buy them in.": "尽管如此，学习的总成本并不取决于您购买它们的顺序。",
    "dilated, making the galaxy effect have speed": "膨胀，使星系效应有速度",
    "Display all goals:": "显示所有目标：",
    "Divide the complexity unlock requirements for complexity challenges by": "将复杂性挑战的复杂性解锁要求除以",
    "don't exist.)": "不存在。）",
    "Double per-boost multiplier": "双倍升压乘数",
    "due to complexities)": "由于复杂）",
    "due to finalities)": "由于最终结果）",
    "Due to unlocking galaxies, you have autobuyers for complexity generators and power upgrades.": "由于解锁了星系，您可以自动购买复杂性生成器和电源升级。",
    "Due to unlocking powers, you gain your eternity points on eternity every second, without needing to eternity (EP generation).": "由于解锁了力量，你每秒获得永恒点数，而无需永恒（EP 生成）。",
    "Each power raises all of a generator type's multipliers to a power. Up to": "每次幂都会将发生器类型的所有乘数提高到一次幂。取决于",
    "EC tier": "EC层",
    "effects are uncapped and raised ^": "效果没有上限和提高 ^",
    "equal to number of Generator": "等于发生器的数量",
    "Equip": "装备",
    "equipped power": "装备电源",
    "Equipped powers from the future:": "来自未来的装备力量：",
    "Equipped powers to constantly load:": "配备持续加载的电源：",
    "Equipped powers:": "装备力量：",
    "eternit": "永恒",
    "eternities": "永恒",
    "eternities in Complexity Challenge": "复杂性挑战中的永恒",
    "eternities to gain permanence.": "永恒以获得永恒。",
    "eternities,": "永恒，",
    "eternities.": "永恒。",
    "eternity": "永恒",
    "Eternity": "永恒",
    "Eternity Autobuyer": "永恒自动购买者",
    "Eternity Challenge": "永恒挑战",
    "eternity challenge (EC) tier": "永恒挑战 (EC) 层级",
    "Eternity challenge requirements and costs are removed, and you can complete multiple eternity challenge tiers at once.": "永恒挑战的要求和成本已被移除，您可以一次完成多个永恒挑战等级。",
    "eternity challenge tier": "永恒挑战等级",
    "eternity challenge tiers, without using automatic eternity challenge completion, in Complexity Challenge": "永恒挑战等级，不使用自动永恒挑战完成，在复杂性挑战中",
    "Eternity Challenges": "永恒的挑战",
    "Eternity challenges lock again once completed.": "永恒挑战完成后再次锁定。",
    "Eternity for": "永恒",
    "Eternity gain": "永恒的收获",
    "Eternity Generator": "永恒发生器",
    "Eternity generators are disabled.": "永恒生成器被禁用。",
    "Eternity generators are multiplied by": "永恒生成器乘以",
    "Eternity generators are multiplied by chroma": "永恒发生器乘以色度",
    "Eternity in": "永恒在",
    "Eternity in Complexity Challenge": "复杂性挑战中的永恒",
    "Eternity Milestone": "永恒里程碑",
    "Eternity Milestones": "永恒里程碑",
    "eternity point": "永恒点",
    "eternity points": "永恒点",
    "eternity points, without buying theorems, in Complexity Challenge": "永恒点，无需购买定理，在复杂性挑战中",
    "Eternity power extra multiplier": "永恒力量额外乘数",
    "Eternity Producer": "永恒制作人",
    "Eternity Producer base production per second:": "Eternity Producer 基础每秒产量：",
    "Eternity Producer multiplier to EGs:": "EG 的 Eternity Producer 乘数：",
    "eternity stars per second.": "每秒永恒的星星。",
    "eternity stars, multiplying all normal and infinity generators by": "永恒星，将所有法线和无穷大发生器乘以",
    "Eternity Upgrades:": "永恒升级：",
    "Eternity:": "永恒：",
    "Eternity: +": "永恒：+",
    "Eternity: Gain": "永恒：获得",
    "Eternity: requires": "永恒：需要",
    "Eternity.": "永恒。",
    "even if they would be otherwise invisible:": "即使它们本来是不可见的：",
    "even pre-complexity.": "甚至是复杂性。",
    "Every time you buy a": "每次买一个",
    "every time you prestige.": "每次你声望。",
    "Exit Infinity Challenge": "退出无限挑战",
    "Exit Normal Challenge": "退出正常挑战",
    "Export equipped powers": "出口装备力量",
    "Export finality shard upgrades": "导出最终分片升级",
    "Export studies": "出口研究",
    "Exported equipped powers (also copied to clipboard):": "导出的装备权力（也复制到剪贴板）：",
    "Exported finality shard upgrades (also copied to clipboard):": "导出的最终分片升级（也复制到剪贴板）：",
    "Exported studies (also copied to clipboard):": "导出的研究（也复制到剪贴板）：",
    "Exporting studies and preset study lists use the same syntax, which is explained below.\n          More of the syntax will be explained as it becomes useful.": "导出研究和预设研究列表使用相同的语法，如下所述。\n 更多语法将在有用时进行解释。",
    "Complexity and resets beyond complexity will reset eternity milestones, and will lock those milestones (including the ones saying \"Start each ... complexity\"), removing their effects until you unlock the milestones again. Once you start with enough eternities after complexity to start with eternity milestones unlocked, however, those milestones will have an effect even at the start of a complexity. This situation will also arise later in the game with other similar mechanics.": "复杂性和超越复杂性的重置将重置永恒里程碑，并将锁定那些里程碑（包括那些说“开始每个......复杂性”的里程碑），在您再次解锁里程碑之前消除它们的影响。 但是，一旦您在复杂性之后从足够的永恒开始以解锁永恒里程碑，即使在复杂性开始时，这些里程碑也会产生影响。 这种情况也会在游戏后期与其他类似机制一起出现。",
    "complexity": "复杂",
    "Complexity": "复杂",
    "complexity achievement": "复杂性成就",
    "Complexity Achievements": "复杂性成就",
    "complexity achievements unlocked:": "复杂性成就解锁：",
    "Complexity Autobuyer": "复杂性自动购买者",
    "complexity challenge": "复杂性挑战",
    "Complexity Challenge": "复杂性挑战",
    "Complexity challenge colors:": "复杂性挑战颜色：",
    "Complexity challenge rewards are currently": "复杂性挑战奖励目前是",
    "complexity challenge tier": "复杂性挑战层",
    "Complexity Challenges": "复杂性挑战",
    "complexity challenges.": "复杂性挑战。",
    "Complexity for": "复杂性",
    "Complexity Generator": "复杂性生成器",
    "Complexity in": "复杂性",
    "complexity point": "复杂点",
    "complexity points": "复杂点",
    "complexity stars per second.": "每秒复杂度星数。",
    "complexity stars this finality, making your complexity star factor": "复杂性成为这个终结的明星，使您的复杂性成为明星因素",
    "complexity stars, making all complexity challenge rewards": "复杂性之星，使所有复杂性挑战得到回报",
    "complexity stars.": "复杂性明星。",
    "complexity stars).": "复杂性星）。",
    "Complexity while in all": "总体上的复杂性",
    "Complexity:": "复杂：",
    "Complexity: +": "复杂性：+",
    "Complexity: Gain": "复杂性：增益",
    "Complexity: requires": "复杂性：需要",
    "Complexity.": "复杂。",
    "constantly increased to your current chroma.": "不断增加到您当前的色度。",
    "Copy export text:": "复制导出文本：",
    "Cost display:": "费用展示：",
    "cost increases are raised ^": "成本增加了^",
    "ℂP/sec,": "ℂP/秒,",
    "ℂP/second.": "ℂP/秒。",
    "Cyan": "青色",
    "Download export text:": "下载导出文本：",
    "Dull brown (": "暗褐色（",
    "Dull cyan (": "暗青色（",
    "Dull gold (": "暗金色（",
    "Dull green (": "暗绿色（",
    "Dull grey (": "暗灰色（",
    "Dull magenta (": "暗洋红 (",
    "Dull orange (": "暗橙色（",
    "Dull purple (": "暗紫色（",
    "Dull red (": "暗红色（",
    "Edge gradients:": "边缘渐变：",
    "EP while in Eternity Challenge": "在永恒挑战中的EP",
    "EP, and you unlock a complexity autobuyer.": "EP，你解锁了一个复杂的自动购买者。",
    "EP, giving": "EP，给予",
    "EP/sec,": "EP/秒，",
    "EP/second.": "EP/秒。",
    "extra galax": "额外的星系",
    "extra infinity point": "额外无穷大点",
    "Extra multiplier from complexity stars and time in complexity": "复杂度星的额外乘数和复杂度时间",
    "Extra multiplier from infinity stars": "来自无限星的额外乘数",
    "Extra multiplier from total strength and rarity of equipped powers": "装备力量的总强度和稀有性的额外乘数",
    "extra purchases.": "额外购买。",
    "extra star": "额外的星星",
    "extra theorem": "额外定理",
    "Extra theorems from green ^": "来自绿色的额外定理 ^",
    "Extra theorems:": "额外定理：",
    "Fast autobuyers": "快速自动购买者",
    "finalit": "最后",
    "finalities": "终局性",
    "finality": "终局性",
    "Finality": "确定性",
    "Finality Autobuyer": "确定性自动购买者",
    "Finality Generator": "确定性生成器",
    "Finality in": "终局性",
    "Finality Milestones": "最终里程碑",
    "finality point": "终结点",
    "Finality point gain on finality (": "终结点获得的终结点 (",
    "Finality presets (": "确定性预设 (",
    "finality presets. Delete existing presets to create more.": "最终性预设。删除现有预设以创建更多预设。",
    "finality shard": "最终分片",
    "finality shard upgrades can be bought up to": "最终分片升级最多可以购买",
    "Finality shard upgrades:": "最终分片升级：",
    "Finality Shards": "最终分片",
    "finality stars per second.": "每秒终结星数。",
    "finality stars, multiplying all non-finality generators by": "终结星，将所有非终结生成器乘以",
    "Finality:": "终局性：",
    "Finality: +": "确定性：+",
    "Finality: Gain": "终局性：增益",
    "Finality: requires": "终局性：需要",
    "Finality.": "终局性。",
    "for a long time.": "需很长时间。",
    "For galaxy effect and eternity power extra multipliers, you start each": "对于星系效应和永恒力量额外乘数，你开始每个",
    "for never):": "永不）：",
    "FP (maxed)": "FP（最大）",
    "FP and": "FP 和",
    "Max upgrades": "最大升级",
    "Minimum rarity of new powers:": "新能力的最低稀有度：",
    "Miscellaneous": "各种各样的",
    "Mixed Engineering": "混合工程",
    "Mixed Logarithm (Sci)": "混合对数 (Sci)",
    "Mixed Scientific": "混合科学",
    "Mode:": "模式：",
    "More colorful than a potato:": "比土豆更鲜艳：",
    "Move explanation back to the top of this tab": "将说明移回此选项卡的顶部",
    "Move explanation to the bottom of this tab": "将说明移至此选项卡的底部",
    "Move the above explanation back to the top of this tab": "将上述说明移回此选项卡的顶部",
    "Move the above explanation to the bottom of this tab": "将上述说明移至此选项卡底部",
    "Multiplier": "乘数",
    "multiplier based on stars (": "基于星星的乘数（",
    "multiplier is raised ^": "乘数提高^",
    "Multiplier per boost": "每次提升的乘数",
    "Multiplier softcap ^": "乘数软帽 ^",
    "Multiplier to boost power gain based on eternity challenge tiers completed (": "根据已完成的永恒挑战等级提高功率增益的乘数（",
    "Multiplier to chroma buildup speed (": "色度累积速度乘数 (",
    "Multiplier to chroma buildup speed based on eternities (currently": "基于永恒的色度累积速度乘数（目前",
    "Multiplier to chroma buildup speed based on total theorems": "基于总定理的色度累积速度乘数",
    "Multiplier to chroma cap (": "乘数到色度上限 (",
    "Multiplier to chroma cap based on theorems (currently": "基于定理的色度上限乘数（目前",
    "Multiplier to EGs based on total EP this complexity:": "基于总 EP 这个复杂性的 EG 乘数：",
    "Multiplier to eternity and permanence gain (": "永恒和永久增益的乘数 (",
    "Multiplier to eternity gain based on complexity achievements unlocked (": "基于解锁复杂性成就的永恒增益乘数（",
    "Multiplier to eternity gain based on eternity challenge tiers completed (": "基于完成的永恒挑战等级的永恒增益乘数（",
    "Multiplier to eternity gain:": "永恒收益的乘数：",
    "Multiplier to eternity generators based on eternity stars and time in eternity": "基于永恒之星和永恒时间的永恒生成器的乘数",
    "Multiplier to eternity generators based on prestige power": "基于声望力量的永恒生成器的乘数",
    "Multiplier to eternity generators based on total theorems": "基于总定理的永恒生成器的乘数",
    "Multiplier to galaxy effect buildup speed (": "星系效应累积速度乘数 (",
    "Multiplier to infinity generators based on eternities": "基于永恒的无穷大生成器的乘数",
    "Multiplier to infinity generators based on number of boosts": "基于提升次数的无穷大生成器的乘数",
    "Multiplier to infinity generators based on prestige power": "基于声望力量的无穷发生器的乘数",
    "Multiplier to infinity generators based on total color value": "基于总颜色值的无穷大生成器的乘数",
    "Multiplier to infinity generators based on total theorems": "基于总定理的无穷大生成器的乘数",
    "Multiplier to normal generators based on prestige power": "基于声望功率的普通发生器乘数",
    "Multiplier to normal generators based on total stars this complexity": "基于总星数的正常生成器的乘数这种复杂性",
    "Multiplier to normal generators based on total theorems": "基于总定理的正常生成器的乘数",
    "Multiplier to permanence based on eternity stars:": "基于永恒之星的永久性乘数：",
    "Multiplier to power gain speed (": "功率增益速度的乘数 (",
    "Multiplier to the per-boost multiplier based on eternities (currently": "基于永恒的每次提升乘数的乘数（目前",
    "multiplier.": "乘数。",
    "multiplier)": "乘数）",
    "multipliers are always": "乘数总是",
    "multipliers are reduced above": "乘数减少到上面",
    "multipliers in reverse order (G8 multiplier larger than G7 multiplier ... larger than G1 multiplier).": "逆序乘数（G8 乘数大于 G7 乘数...大于 G1 乘数）。",
    "multiplying all generators": "将所有生成器相乘",
    "multiplying permanence and chroma buildup speed by": "将持久性和色度累积速度乘以",
    "must be the first color you unlock.": "必须是您解锁的第一个颜色。",
    "Name:": "姓名：",
    "never auto-completing an EC tier": "从不自动完成 EC 层",
    "new power": "新势力",
    "New powers can be stored up by turning power gain off. When it's turned on again you'll get all the new powers at once.": "可以通过关闭功率增益来存储新的功率。当它再次打开时，您将立即获得所有新功能。",
    "New powers generally have a random type and random rarity.": "新异能一般具有随机类型和随机稀有度。",
    "News (non-game-relevant messages at top of screen):": "新闻（屏幕顶部与游戏无关的消息）：",
    "next": "下一个",
    "Next complexity": "下一个复杂性",
    "next finality.": "下一个结局。",
    "Next galaxies are at": "下一个星系在",
    "next in": "下一个",
    "Next power": "下一个权力",
    "Next theorem at": "下一个定理",
    "Next:": "下一个：",
    "No extra multiplier": "没有额外的乘数",
    "No requirement (you're always in this challenge).": "没有要求（你总是在这个挑战中）。",
    "None": "没有任何",
    "normal": "普通的",
    "Normal": "普通的",
    "normal challenge": "正常挑战",
    "Normal Challenge": "普通挑战",
    "Normal Challenges": "正常挑战",
    "Normal Challenges:": "正常挑战：",
    "normal challenges.": "正常的挑战。",
    "Not on by default due to ℂP generation": "由于 ℂP 生成，默认情况下未启用",
    "Not on by default due to EP generation": "由于 EP 生成，默认情况下未启用",
    "Not on by default due to IP generation": "由于 IP 生成，默认情况下未启用",
    "Not on by default due to permanence generation": "由于永久生成，默认情况下未启用",
    "Notation on times:": "时间符号：",
    "Notation:": "符号：",
    "Note that you can put fourth-row studies (that is, numbers from 13 to 16) in this list, but there is a more convenient syntax for fourth-row studies explained below.": "请注意，您可以将第四行研究（即从 13 到 16 的数字）放在此列表中，但下面解释了第四行研究的更方便的语法。",
    "Note that you cannot benefit from the Eternity Producer or buy Eternity Producer upgrades before you unlock the Eternity Producer.": "请注意，在解锁 Eternity Producer 之前，您无法从 Eternity Producer 中受益或购买 Eternity Producer 升级。",
    "Note that you cannot gain chroma before you unlock any color of it, and": "请注意，在解锁任何颜色之前，您无法获得色度，并且",
    "Note that you cannot gain powers or buy power upgrades before you unlock powers.": "请注意，在解锁权力之前，您无法获得权力或购买权力升级。",
    "Note that you cannot get a prediction from the Oracle before you unlock the Oracle.": "请注意，在解锁 Oracle 之前，您无法从 Oracle 获得预测。",
    "Note that you cannot get any galaxies before galaxies are unlocked.": "请注意，在星系解锁之前，您无法获得任何星系。",
    "Number of achievements beyond last reached achievement to show:": "要显示的超出上一次达到的成就的成就数量：",
    "Number of last runs of each type to show:": "要显示的每种类型的最后运行次数：",
    "of each type are useless and are thus automatically deleted for power shards.": "每种类型的都是无用的，因此会被自动删除以用于 power shards。",
    "of every": "每一个",
    "of rarities.": "的稀有。",
    "Offline game ticks (between": "离线游戏滴答（之间",
    "Offline progress:": "离线进度：",
    "On:": "开启：",
    "Once you understand this explanation, you can move it to the bottom of this tab so that it doesn't take up so much space.": "一旦你理解了这个解释，你可以把它移到这个标签的底部，这样它就不会占用太多空间。",
    "Only achievements up to": "只有成就达到",
    "Options": "选项",
    "Options: cannot be hidden": "选项：不能隐藏",
    "Oracle": "甲骨文",
    "Loading the study list a,b,c,...,z tries to buy Study a, then Study b, then Study c, and so on, until it has bought Study z.\n          If the game cannot buy a study in the list with the available theorems, it will continue to the next study in the list rather than stopping.": "加载研究列表 a,b,c,...,z 尝试购买研究 a，然后研究 b，然后研究 c，依此类推，直到它购买研究 z。\n 如果游戏无法购买研究 与可用定理的列表，它将继续到列表中的下一个研究而不是停止。",
    "Import color scheme": "导入配色方案",
    "Import equipped powers": "进口装备电源",
    "Import finality shard upgrades": "导入最终分片升级",
    "Import studies": "导入研究",
    "Import tabs to show": "导入选项卡以显示",
    "Import/Load": "导入/加载",
    "in": "在",
    "in Complexity Challenge": "在复杂性挑战中",
    "In particular, when starting a new complexity, you will be in all complexity challenges that you've unlocked at once.": "特别是，当开始一个新的复杂性时，您将面临一次解锁的所有复杂性挑战。",
    "in this complexity, increasing chroma caps ^": "在这种复杂性中，增加色度上限 ^",
    "in this complexity.": "在这种复杂性中。",
    "in this complexity)": "在这种复杂性中）",
    "in this eternity, giving you": "在这永恒中，给你",
    "in this eternity.": "在这永恒中。",
    "in this eternity)": "在这永恒中）",
    "in this finality.": "在这个终结中。",
    "in this finality)": "在这个终结中）",
    "in this infinity.": "在这无限中。",
    "in this infinity)": "在这个无限中）",
    "in this prestige.": "在此声望。",
    "Increase the base multiplier per boost:": "增加每次提升的基础乘数：",
    "Increase the multiplier per boost:": "增加每次提升的乘数：",
    "Increase the per-purchase complexity generator multiplier based on best boost power (currently": "根据最佳升压功率增加每次购买的复杂度生成器乘数（目前",
    "Increase the per-purchase multiplier for EGs:": "增加 EG 的每次购买乘数：",
    "Increase the power of infinity stars:": "增加无限星的力量：",
    "Increase to strength of new powers (": "增加新力量的力量（",
    "increasing linearly from": "从线性增加",
    "infinit": "无限",
    "infinities.": "无穷大。",
    "infinity": "无穷",
    "Infinity": "无穷",
    "Infinity Autobuyer": "无限自动购买者",
    "infinity challenge": "无限挑战",
    "Infinity Challenge": "无限挑战",
    "Infinity Challenges": "无限挑战",
    "Infinity Challenges:": "无限挑战：",
    "Infinity Generator": "无穷大发生器",
    "Infinity generator multipliers are square-rooted (^": "无穷大生成器乘数是平方根 (^",
    "Infinity generator per-purchase multipliers are disabled.": "Infinity 生成器每次购买乘数被禁用。",
    "Infinity generators are disabled.": "无穷大发生器被禁用。",
    "Infinity in Infinity Challenge": "无限挑战中的无限",
    "Infinity in Normal Challenge": "正常挑战中的无限",
    "infinity point": "无穷大点",
    "infinity stars per second.": "每秒有无数颗星星。",
    "infinity stars, multiplying all": "无限的星星，乘以所有",
    "Infinity Upgrades:": "无限升级：",
    "Infinity:": "无穷：",
    "Infinity: +": "无穷大：+",
    "Infinity: Gain": "无限：增益",
    "Infinity: requires": "无穷大：需要",
    "Infinity.": "无穷。",
    "Instead, violating the condition makes you exit the challenge.": "相反，违反条件会让您退出挑战。",
    "Instead, violating the condition makes you exit the complexity challenge.": "相反，违反条件会使您退出复杂性挑战。",
    "into the future,": "走向未来，",
    "into the future, using": "未来，使用",
    "IP, giving": "知识产权，给予",
    "IP/sec,": "IP/秒，",
    "IP/second.": "IP/秒。",
    "is": "是",
    "is added to the multiplier per boost.": "每次提升都会添加到乘数中。",
    "It can also be used to see what powers you would gain with power gain on.": "它也可以用来查看在功率增益开启后你会获得什么功率。",
    "It can be improved via upgrades.": "它可以通过升级来改进。",
    "It is generally not recommended to delete any of your first few powers to get power shards.": "通常不建议删除前几个权力中的任何一个来获得权力碎片。",
    "It is impossible to get more than": "不可能超过",
    "It will also multiply all eternity generators by": "它还将所有永恒生成器乘以",
    "Keep already-obtained completions of each complexity challenge on": "保持每个复杂性挑战的已经完成",
    "Large fixed multiplier to normal generators": "普通发生器的大固定乘数",
    "Last complexity took": "最后的复杂性",
    "Last eternity took": "最后的永恒",
    "Last finality took": "最后的最终结果",
    "Last infinity took": "最后一个无穷大",
    "Last Ten Runs": "最后十次运行",
    "Last Ten Runs:": "最后十次运行：",
    "Letters": "信件",
    "Load": "加载",
    "log ℂP/sec,": "记录ℂP/秒，",
    "log ℂP/second.": "记录ℂP/秒。",
    "log EP/sec,": "记录 EP/秒，",
    "log EP/second.": "记录 EP/秒。",
    "log IP/sec,": "记录 IP/秒，",
    "log IP/second.": "记录 IP/秒。",
    "Logarithm": "对数",
    "Lose all but": "失去一切，但",
    "Magenta": "品红",
    "Main": "主界面",
    "Main:": "主要的：",
    "Make autobuyers trigger at most every X seconds (": "让自动购买者最多每 X 秒触发一次（",
    "making the finality generator per-purchase multiplier": "使最终生成器每次购买乘数",
    "Max": "最大限度",
    "Max all": "最大所有",
    "Max all normal generators and boosts": "最大化所有正常的发生器和助推器",
    "Max Eternity Producer upgrades": "Max Eternity Producer 升级",
    "Max fourth-row studies": "最大第四行研究",
    "Max generators": "最大发生器",
    "Max permanence upgrades": "最大永久升级",
    "Max power shard upgrades": "最大功率碎片升级",
    "Max power upgrades": "最大功率升级",
    "Oracle:": "甲骨文：",
    "Orange": "橘色",
    "other than Generator": "除了发生器",
    "permanence.": "永久性。",
    "permanence. You get": "永久性。你得到",
    "playing this game (counting time offline).": "玩这个游戏（离线计算时间）。",
    "playing this game (only counting time online).": "玩这个游戏（只计算在线时间）。",
    "power": "力量",
    "Power deletion:": "电源删除：",
    "Power gain in predictions:": "预测中的功率增益：",
    "Power gain:": "功率增益：",
    "power of each type but get more over time. You can have multiple powers of the same type equipped.": "每种类型的力量，但随着时间的推移会得到更多。您可以装备多个相同类型的力量。",
    "Power presets (": "电源预设（",
    "power presets. Delete existing presets to create more.": "电源预设。删除现有预设以创建更多预设。",
    "power shard": "电源分片",
    "Power shard upgrade multipliers take effect after power and rarity, but before extra multipliers.": "能量碎片升级乘数在能量和稀有度之后生效，但在额外乘数之前。",
    "power shards": "电源碎片",
    "Power shards can be used to buy upgrades that give powers small additional multipliers, and to craft new powers.": "能量碎片可用于购买赋予能量小的额外乘数的升级，以及制作新的能量。",
    "power shards.": "电源碎片。",
    "power shards)": "能量碎片）",
    "Power to Eternity Producer multiplier to EGs:": "EG 的 Eternity Producer 乘数：",
    "Power to fourth-row study effects based on per-boost multiplier (currently ^": "基于每次提升乘数的第四行研究效果的功效（目前 ^",
    "Power to non-finality generator multipliers (": "非确定性生成器乘数的功率（",
    "Power to third-row study effects:": "第三排研究效果的力量：",
    "Powers": "权力",
    "Powers are never destroyed unless you delete them, or unless they're automatically deleted as explained on this tab below stored powers.": "除非您删除它们，或者除非它们被自动删除，否则权力永远不会被破坏，如存储权力下方的此选项卡中所述。",
    "Powers can be equipped at any time as long as there is a free slot.": "只要有空位，就可以随时装备力量。",
    "Powers unequip:": "权力解除：",
    "Powers:": "权力：",
    "Pre-set locked reset autobuyers (this overrides the above setting):": "预设锁定重置自动购买者（这会覆盖上述设置）：",
    "Preset change:": "预设更改：",
    "Preset deletion:": "预设删除：",
    "Preset highlight colors:": "预设高亮颜色：",
    "Presets (": "预设（",
    "Presets can be used to load study lists more easily.": "预设可用于更轻松地加载研究列表。",
    "presets. Delete existing presets to create more.": "预设。删除现有预设以创建更多预设。",
    "Prestige Autobuyer": "威望自动购买者",
    "Prestige no longer resets anything.": "威望不再重置任何东西。",
    "Prestige power is raised ^": "威力提升^",
    "prestige power multiplying all": "威望力量倍增",
    "Prestige:": "声望：",
    "Prestige.": "声望。",
    "Prime": "主要的",
    "Produce": "生产",
    "purchases):": "购买）：",
    "purchases).": "购买）。",
    "Purple": "紫色的",
    "Rebuy studies when finishing ℂC6:": "完成ℂC6时重新购买研究：",
    "Red": "红色的",
    "Reload window": "重新加载窗口",
    "Reloading might work, so probably try that first.": "重新加载可能会起作用，所以可能先尝试一下。",
    "remaining": "其余的",
    "Remove the complexity unlock requirements for complexity challenges, and always have autobuyers for complexity generator and power upgrades.": "消除复杂性挑战的复杂性解锁要求，并始终为复杂性生成器和电源升级提供自动购买者。",
    "Remove this message": "删除此消息",
    "Remove this message for now": "暂时删除此消息",
    "Requirement to start:": "启动要求：",
    "Requirement to unlock:": "解锁要求：",
    "Reset buttons for hidden tabs:": "隐藏标签的重置按钮：",
    "Reset colors:": "重置颜色：",
    "Reset dilated galaxies to": "将膨胀的星系重置为",
    "Reset it (": "重置它（",
    "Reset it (exit and start again)": "重置它（退出并重新开始）",
    "RESET THE GAME": "重置游戏",
    "Respec eternity challenge and": "尊重永恒的挑战和",
    "Respec eternity challenge on next eternity:": "尊重下一个永恒的永恒挑战：",
    "Respec finality shard upgrades and": "尊重最终分片升级和",
    "Respec finality shard upgrades on next finality:": "Respec 在下一个 finality 上进行 finality 分片升级：",
    "Respec finality shard upgrades when loading a preset:": "加载预设时注意最终分片升级：",
    "Respec fourth-row studies and": "尊重第四行研究和",
    "Respec studies and": "尊重研究和",
    "Respec studies on next eternity:": "尊重下一个永恒的研究：",
    "Respec studies when loading a preset:": "加载预设时重新指定研究：",
    "Restart complexity and re-enter all complexity challenges": "重新启动复杂性并重新进入所有复杂性挑战",
    "Restart infinity challenges on completion:": "完成后重新启动无限挑战：",
    "Restart normal challenges on completion:": "完成后重新开始正常挑战：",
    "Return to default color scheme": "返回默认配色方案",
    "reward is instead currently": "奖励是目前",
    "reward strength and complexity star factor.": "奖励强度和复杂性明星因素。",
    "reward strength and total complexity stars are based on hypercomplexity stars, which are what your complexity stars would be if your complexity power": "奖励强度和总复杂性星基于超复杂性星，如果你的复杂性能力，这就是你的复杂性星",
    "Roman": "罗马",
    "Run types to show:": "要显示的运行类型：",
    "Save/load notifications:": "保存/加载通知：",
    "Scientific": "科学的",
    "scripts (should be 91).": "脚本（应该是 91）。",
    "second": "第二",
    "Seconds to reach cap": "达到上限的秒数",
    "Set craft rarity to maximum possible (": "将工艺稀有度设置为最大可能（",
    "Show (now unneeded) eternity challenge requirements:": "显示（现在不需要）永恒挑战要求：",
    "Show all unlocked tabs": "显示所有未锁定的标签",
    "Show color options": "显示颜色选项",
    "Show completed achievement rows:": "显示完成的成就行：",
    "Show explanation of presets and exported studies:": "显示预设和导出研究的说明：",
    "Show export reminder after X seconds (": "X 秒后显示导出提醒 (",
    "Show export text:": "显示导出文本：",
    "Show fully-question-mark achievement rows:": "显示全问号成就行：",
    "Show future power extra multipliers (as opposed to current):": "显示未来的功率额外乘数（相对于当前）：",
    "Show future powers on prediction:": "显示预测的未来力量：",
    "Show generator and boost autobuyers:": "显示生成器并提升自动购买者：",
    "Show other options": "显示其他选项",
    "Show saving options": "显示保存选项",
    "Show tab options": "显示选项卡选项",
    "Show waiting time from when prediction was made (as opposed to current):": "显示从做出预测开始的等待时间（相对于当前）：",
    "Single power unequip:": "单电源不装备：",
    "Single study refund:": "单次学习退款：",
    "Slow": "减缓",
    "Slow autobuyers will trigger in": "缓慢的自动购买者将触发",
    "Slow down offline progress (doing more ticks but being more accurate)": "减慢离线进度（做更多滴答但更准确）",
    "Smaller header:": "较小的标题：",
    "sort by name": "按名称分类",
    "Speed of gaining new powers:": "获得新能力的速度：",
    "Speed up offline progress (doing fewer ticks)": "加快离线进度（做更少的滴答声）",
    "square root of": "的平方根",
    "Standard": "标准",
    "stars": "星星",
    "stars per second.": "每秒星星。",
    "stars this complexity.": "明星这种复杂性。",
    "stars this eternity": "星辰这永恒",
    "stars this eternity.": "这个永恒的星星。",
    "stars this finality.": "明星这个结局。",
    "stars to infinity.": "星星到无穷大。",
    "stars.": "星星。",
    "stars. You are getting": "星星。你得到",
    "Start each": "开始每个",
    "Statistics:": "统计数据：",
    "stellar product and": "明星产品和",
    "Stored powers from the future:": "来自未来的储存力量：",
    "Stored powers:": "储存的力量：",
    "Strength of new powers:": "新势力的实力：",
    "Studies": "学习",
    "studies in Complexity Challenge": "复杂性挑战研究",
    "Studies on the fourth row are rebuyable, with increasing costs.": "第四行的研究是可重复购买的，但成本会增加。",
    "Studies respec:": "研究方面：",
    "Studies:": "学习：",
    "Study": "学习",
    "Study click mode:": "学习点击模式：",
    "Study list to constantly load:": "学习列表不断加载：",
    "Study list:": "学习清单：",
    "Swap your equipped powers with better stored powers of the same type and": "用相同类型的更好存储的力量交换你装备的力量和",
    "Synchronize slow and fast autobuyers": "同步慢速和快速自动购买者",
    "Tab colors:": "标签颜色：",
    "Tab presets (": "选项卡预设 (",
    "tab presets. Delete existing presets to create more.": "选项卡预设。删除现有预设以创建更多预设。",
    "Tabs to show:": "要显示的标签：",
    "Thanks to jdawson7 (clarifying strategy, improving guide), eQueline (suggesting many great QoL features), and Kyleptune (suggesting the ability to change colors).": "感谢 jdawson7（阐明策略、改进指南）、eQueline（提出了许多出色的 QoL 功能）和 Kyleptune（提出了改变颜色的能力）。",
    "Thanks to the testers (Boo, Dravitar, Earth, Omsi, Pichu, Sere, SpectralFlame, others, and Jazz) for testing before release and suggesting features.": "感谢测试人员（Boo、Dravitar、Earth、Omsi、Pichu、Sere、SpectralFlame、其他和 Jazz）在发布前进行测试并提出功能建议。",
    "Thanks to Universal Attractor (pre-infinity) and Antimatter Dimensions for game mechanics.": "感谢 Universal Attractor (pre-infinity) 和 Antimatter Dimensions 的游戏机制。",
    "The": "",
    "The ability to disable certain things is there to prevent accidental violation of complexity challenge requirements.": "禁用某些东西的能力是为了防止意外违反复杂性挑战要求。",
    "The calculation of which powers are the best": "计算哪种幂是最好的",
    "The complexity autobuyer is off when unlocked unless you explicitly pre-set it to be on.": "除非您明确将其预先设置为开启，否则复杂性自动购买器在解锁时会关闭。",
    "The Complexity Challenge": "复杂性挑战",
    "The complexity eight complexities ago took": "八个复杂性之前的复杂性",
    "The complexity five complexities ago took": "五个复杂性之前的复杂性",
    "The complexity four complexities ago took": "四个复杂度前的复杂度",
    "The complexity nine complexities ago took": "九个复杂性之前的复杂性",
    "The complexity seven complexities ago took": "七个复杂性之前的复杂性",
    "The complexity six complexities ago took": "六个复杂性之前的复杂性",
    "The complexity ten complexities ago took": "十个复杂性之前的复杂性",
    "The complexity three complexities ago took": "三个复杂性之前的复杂性",
    "The complexity two complexities ago took": "两个复杂性之前的复杂性",
    "The eternity eight eternities ago took": "八个永恒前的永恒",
    "The eternity five eternities ago took": "五个永恒前的永恒",
    "The eternity four eternities ago took": "四个永恒前的永恒",
    "The eternity nine eternities ago took": "九个永恒前的永恒",
    "The Eternity Producer is producing": "永恒制作人正在制作",
    "The Eternity Producer, when unlocked, will produce": "永恒生产者解锁后将生产",
    "The eternity seven eternities ago took": "七个永恒前的永恒",
    "The eternity six eternities ago took": "六个永恒前的永恒",
    "The eternity ten eternities ago took": "十个永恒前的永恒",
    "The eternity three eternities ago took": "三个永恒前的永恒",
    "The eternity two eternities ago took": "两个永恒前的永恒",
    "The finality eight finalities ago took": "八项终结前的终结",
    "The finality five finalities ago took": "五个结局前的结局",
    "The finality four finalities ago took": "最终确定性四个最终确定性采取了",
    "The finality nine finalities ago took": "九个结局前的结局",
    "The finality seven finalities ago took": "七项决赛前的决赛",
    "The finality six finalities ago took": "六年前的最终确定",
    "The finality ten finalities ago took": "十个结局前的结局",
    "The finality three finalities ago took": "三个结局前的结局",
    "The finality two finalities ago took": "两个结局前的结局",
    "The first": "首先",
    "The game is loading; this message should only appear for a few seconds.": "游戏正在加载；此消息应仅显示几秒钟。",
    "The header does not mention that you are in Complexity Challenge": "标题没有提到您在复杂性挑战中",
    "The infinity eight infinities ago took": "八无穷前的无穷大",
    "The infinity five infinities ago took": "无限五无限之前",
    "The infinity four infinities ago took": "四无穷前的无穷",
    "The infinity nine infinities ago took": "无穷九无穷之前",
    "The infinity seven infinities ago took": "无穷七无穷之前",
    "The infinity six infinities ago took": "无穷六无穷前取",
    "The infinity ten infinities ago took": "十无限前的无限",
    "The infinity three infinities ago took": "三个无限前的无限",
    "The infinity two infinities ago took": "两个无穷大之前的无穷大",
    "The multiplier to permanence and chroma from complexities also applies to boost power (currently": "复杂性对持久性和色度的乘数也适用于增强功率（目前",
    "The Oracle can look between": "Oracle 可以查看",
    "The Oracle is a quality-of-life feature that will let you see the future.": "Oracle 是一种生活质量功能，可让您看到未来。",
    "The Oracle lets you see what certain stats will be and what powers you will gain in the future.": "Oracle 让您了解某些统计数据以及您将来将获得哪些权力。",
    "The page loads": "页面加载",
    "The powers equipped by importing powers will be the strongest stored powers of the chosen types.": "导入异能所装备的异能将是所选类型中最强的储存异能。",
    "The prestige power formula alternates between being raised ^": "威能公式在被提升之间交替进行^",
    "The prestige power formula is worse the more prestiges you do.": "你做的声望越多，声望力量公式就越差。",
    "The value of whatever color you are producing is": "您生产的任何颜色的价值是",
    "The values of all colors are": "所有颜色的值都是",
    "Their costs are unaffected by buying other studies. Their shown costs are always the cost of the next purchase.": "他们的成本不受购买其他研究的影响。他们显示的成本始终是下一次购买的成本。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);