/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "x total IP each time (though it's OK to infinity earlier if that would let you get a new infinity generator that you don't have yet). You can do roughly this (definitely close enough) with the infinity autobuyer by setting its mode to \"X times best of last ten\" and its input to": "每次 x 总 IP（尽管如果可以让您获得尚未拥有的新无穷大生成器，则可以提前无穷大）。 您可以通过将其模式设置为“X 次最好的过去 10 次”并将其输入设置为",
    "x total IP per infinity at this point, your infinities are probably too long. You may want to get a bit more IP than the price of whatever you want to purchase, so that you can also buy some cheap infinity generators. Infinities will get longer at first, getting as long as": "x 此时每个无穷大的总 IP，你的无穷大可能太长了。 您可能希望获得比您想购买的任何价格更多的 IP，以便您还可以购买一些便宜的无穷大发生器。 一开始无穷大会变长，只要",
    "x. However, note that whenever you set the prestige autobuyer or another reset autobuyer (such as the infinity autobuyer) based on time, if you go offline, ticks will be longer and so the autobuyer may trigger every few ticks, which may not let production build up enough. So if you go offline, you may want to adjust your reset autobuyers to trigger less often or instead be based on multiplier.": "X。 但是，请注意，每当您根据时间设置声望自动购买者或其他重置自动购买者（例如无限自动购买者）时，如果您下线，滴答时间会更长，因此自动购买者可能每隔几个滴答时间触发一次，这可能不会让生产建立 够了。 因此，如果您离线，您可能需要调整重置自动购买者以减少触发频率，或者改为基于乘数。",
    "x multiplier to each normal generator. This will, as before, make your next few infinities far quicker. Also, due to your extra infinity generators making infinity stars increase faster and thus making longer infinities better, start to infinity for": "每个正常生成器的 x 乘数。 和以前一样，这将使您接下来的几个无穷大更快。 此外，由于您的额外无穷大发生器使无穷大恒星增长得更快，从而使更长的无穷大更好，开始无穷大",
    "You can do Normal Challenge 1 right now. If you want to do so, you should read below about normal challenges and Normal Challenge 1 in particular. Do another infinity, whether or not you do it in Normal Challenge 1, generally following the parts of the guide above this (except that you don't need to unlock slow autobuyers, since they're already unlocked). It'll be a lot quicker (probably at least": "您现在可以进行普通挑战 1。 如果你想这样做，你应该阅读下面的普通挑战，特别是普通挑战 1。 做另一个无限，不管你是否在普通挑战 1 中做，通常按照上面指南的部分进行（除了你不需要解锁慢速自动购买者，因为他们已经解锁了）。 它会快很多（可能至少",
    "You get complexity achievements for getting certain amounts of progression in complexity challenges. Complexity achievements have various types of rewards of varying significance. Right now you'll want the first two complexity achievements, \"One per generator\" and \"Forever isn't too long\". (Without ℂC1x2, which is what this section of the guide was originally written for, \"Forever isn't too long\" will take roughly": "您可以通过在复杂性挑战中取得一定程度的进步而获得复杂性成就。 复杂性成就具有不同意义的各种类型的奖励。 现在您需要前两个复杂性成就，“每个生成器一个”和“永远不会太长”。 （如果没有 ℂC1x2，这是本指南最初编写的内容，“永远不会太长”将大致花费",
    "You should do your first infinity in Normal Challenge 12, because the condition does nothing and you'll get an autobuyer and a small multiplier for it. You don't need to unlock slow autobuyers again, since they're already unlocked. Normal Challenge 1 is comparatively harder, because the multiplier from eternity stars only applies to": "你应该在 普通挑战 12 中做你的第一个无限，因为条件什么都不做，你会得到一个自动购买者和一个小的乘数。 您无需再次解锁慢速自动购买者，因为它们已经解锁。 普通挑战 1 相对更难，因为来自永恒之星的乘数只适用于",
    "x best of last ten is good even just after Infinity Challenge 1, for the rest of the eternity. If you want, you can do slightly better manually early on by doing slightly longer infinities, because of how powerful Infinity Challenge 1 is (also note what was said above about starting an infinity challenge immediately after unlock). Infinity Challenge 4 is not far quicker; it's not worth doing and should be skipped. Because you start with": "即使在无限挑战 1 之后，x 最好的最后十个也是好的，对于永恒的其余部分。 如果你愿意，你可以在早期手动做稍微长一点的无限，因为无限挑战 1 是多么强大（还要注意上面所说的关于在解锁后立即开始无限挑战的内容）。 无限挑战 4 也快不了多少。 这不值得做，应该跳过。 因为你从",
    "When you sacrifice, you'll be asked if you're sure you want to. You should say yes. This is a measure to stop accidental sacrifices at bad times for it. Turn it off in the options tab (in the confirmations row) when you feel that the safety of not accidentally sacrificing stops being worthwhile. This applies to other confirmations too.": "当您牺牲时，系统会询问您是否确定要这样做。 你应该说是的。 这是一种在困难时期阻止意外牺牲的措施。 当您觉得不意外牺牲的安全性不再值得时，请在选项选项卡（在确认行中）将其关闭。 这也适用于其他确认。",
    "when bought. Thirdly, after buying Generator 8, you will be able to sacrifice. It doesn't matter very much for what multiplier you do this the first time, but I would recommend at least": "买的时候。第三，购买 发生器 8后，您将可以牺牲。你第一次这样做的乘数并不重要，但我至少会推荐",
    "When you complete all the challenges, break infinity. Set the sacrifice autobuyer to": "当你完成所有挑战时，打破无限。将牺牲自动购买者设置为",
    "When you get": "当你拿到时",
    "When you have": "当你有",
    "when you prestige is not bad, but having": "当你声望不差，但有",
    "When you unlock cyan, first get": "当你解锁青色时，首先得到",
    "which is already boughts,": "已经买了，",
    "With your": "和你的",
    "x (though it barely matters). Eventually you'll be able to prestige again. In theory, the optimal prestige powers amounts to prestige at are roughly": "x（尽管它几乎不重要）。最终你将能够再次声望。理论上，最佳威望威力相当于威望大约是",
    "x additional multiplier to generators. After you infinity for the third time, you'll have": "x 生成器的附加乘数。在你第三次无限之后，你将拥有",
    "x after finishing the challenge. It's not clear if doing this challenge is actually worthwhile, given how close eternity is.": "x 完成挑战后。考虑到永恒有多近，目前尚不清楚进行这项挑战是否真的值得。",
    "x and": "x 和",
    "x and set the prestige autobuyer to": "x 并将声望自动购买者设置为",
    "x and since you have": "x 因为你有",
    "x and the challenge will take roughly as long as it would otherwise, because you still have to wait for infinity stars to build up. This is a rather fast infinity challenge, taking only roughly": "x 并且挑战将花费大约与其他情况一样长的时间，因为您仍然需要等待无穷大的恒星建立。这是一个相当快的无限挑战，只需要大致",
    "x and the infinity autobuyer": "x 和无限自动购买者",
    "x and you'll have a lot of purchases left over if you follow the advice here. For all prestiges but your last, buy only": "x 如果您遵循此处的建议，您将有很多剩余购买。对于所有声望，但您的最后一次，只购买",
    "x as fast. The strategy is similar to that for second eternity, except that you don't need to do challenges, and there's thus no reason to do your first infinity in Normal Challenge 12. Remember to set your prestige autobuyer back to": "x 一样快。策略类似于第二个永恒，除了你不需要挑战，因此没有理由在普通挑战12中进行你的第一个无限。记得将你的声望自动购买设置回",
    "x as good as a": "x 和 a 一样好",
    "x best of last ten rather than, for example, every": "x 最好的最后十个，而不是，例如，每个",
    "x best of last ten within EC1x2. EC1x2 will take roughly": "x 在 EC1x2 内的最后十个中最好的。 EC1x2 大约需要",
    "x best of last ten within EC3x1. EC3x1 should take at most roughly": "x 在 EC3x1 中的最后十个中最好的。 EC3x1 最多大概需要",
    "x best of last ten, or try to slightly improve on this with manual prestige and infinity. You should still eternity for": "x 最好的最后十个，或者尝试通过手动声望和无限来稍微改进这一点。你应该仍然永恒",
    "x best of last ten. Do eternities for": "x 最好的最后十个。做永恒",
    "x best of last ten. Keep the infinity autobuyer at": "x 最好的最后十个。将无限自动购买者保持在",
    "x best of last ten. You should be able to get another theorem with stars and another theorem with IP in": "x 最好的最后十个。你应该能够得到另一个带有星星的定理和另一个带有 IP 的定理",
    "x EP in": "x EP 输入",
    "x EP per eternity. At": "x EP 永恒。在",
    "x EP with them; from this point on, every eternity challenge completion will be a rather large benefit to progress, and progress will slow down somewhat directly before the next eternity challenge completion. At": "x EP 与他们；从这点开始，每一次永恒挑战完成都会对进度有相当大的好处，而在下一次永恒挑战完成之前进度会稍微放缓。在",
    "x EP. Once you have": "x EP。一旦你有",
    "x faster (infinity generators are all multiplied by min(": "x 更快（无穷大生成器都乘以 min(",
    "x faster. Then get": "x 更快。然后得到",
    "x faster. When you can next get": "x 更快。下次什么时候可以得到",
    "x faster. You can get to": "x 更快。你可以到达",
    "x generally being better early and larger multipliers like": "x 通常是更好的早期和更大的乘数，例如",
    "x generally being better late. If you're about to be able to get a theorem, wait for it. Generally, almost all eternities should be less than": "x 通常迟到会更好。如果您将能够得到一个定理，请等待它。一般来说，几乎所有的永恒都应该小于",
    "x in general, though your first eternity after EC3x1 and EC4x1 might give you even more EP than that (your eternities should be at least": "x 一般来说，虽然你在 EC3x1 和 EC4x1 之后的第一个永恒可能会给你更多的 EP（你的永恒应该至少",
    "x initially) to eternity gain. You'll soon (in": "x 最初）到永恒的增益。你很快就会（在",
    "x IP rather than": "x IP 而不是",
    "x is not that bad.": "x 没那么糟糕。",
    "x multiplier is only": "x 乘数仅",
    "x multiplier to all generators for every": "每个生成器的 x 乘数",
    "x multiplier to all generators, which will let you get far more quickly to where you were before. You also keep your slow autobuyers. Keep playing as before, perhaps sacrificing slightly later, at perhaps": "x 乘数到所有生成器，这将使您更快地回到以前的位置。您还保留了缓慢的自动购买者。像以前一样继续玩，也许稍后会牺牲，也许",
    "x multiplier to normal generators from having produced": "x 乘数到正常生成器从产生",
    "x multiplier to normal generators). It's interesting to note that it actually gets smaller as you progress, not just in comparison to your stars but overall. Still, infinities should only be roughly": "x 乘数到正常生成器）。有趣的是，随着你的进步，它实际上会变小，不仅仅是与你的星星相比，而是整体而言。尽管如此，无穷大应该只是粗略的",
    "x multiplier to the same thing, since": "x 乘以相同的东西，因为",
    "x multiplier, which is a very big speedup. You can also set the infinity autobuyer to infinity": "x 乘数，这是一个非常大的加速。您还可以将 infinity autobuyer 设置为 infinity",
    "x multiplier. Then turn autobuyers on. Once you have": "x 乘数。然后开启自动购买。一旦你有",
    "x multiplier. This means that your next few infinities will be very quick; for example, you can now get enough IP to buy Infinity Generator 6 for the first time (": "x 乘数。这意味着你接下来的几个无穷大将非常快；例如，您现在可以获得足够的 IP 来首次购买 Infinity Generator 6（",
    "x or": "x 或",
    "x prestige multiplier if you first prestiged for": "x声望乘数，如果你第一次声望",
    "x quicker), since you'll have a": "x 更快），因为你会有一个",
    "x rather than": "x 而不是",
    "x the price of a new infinity generator or an infinity upgrade, you shouldn't buy them).": "x 一个新的无限发电机或无限升级的价格，你不应该买它们）。",
    "x to": "x 到",
    "x total EP. Getting": "x 总 EP。得到",
    "x until you complete IC1. This eternity will be roughly the same length as the previous one.": "x 直到完成 IC1。这个永恒与前一个永恒的长度大致相同。",
    "x until you complete IC1. You still want to do some early infinities for": "x 直到完成 IC1。你仍然想为",
    "x your current stars.": "x 你目前的星星。",
    "x your total EP in each eternity, with smaller multipliers like": "x 你在每个永恒中的总 EP，乘数较小，如",
    "x, and getting the boost with cost": "x，并获得成本提升",
    "x, and, if you do Normal Challenge 12 earlier than suggested here, infinity whenever possible, at least before breaking infinity (multiple settings lead to this).": "x，并且，如果您比此处建议的时间更早进行 Normal Challenge 12，则尽可能无限，至少在打破无限之前（多个设置会导致这种情况）。",
    "x, as you should do. At this point, eternities are roughly": "x，你应该做的。在这一点上，永恒大致是",
    "x, gets faster with more eternities": "x，随着更多的永恒而变得更快",
    "x, per purchase.": "x，每次购买。",
    "x, prestige for multiplier": "x，乘数的威望",
    "x, takes": "x, 需要",
    "x. EC1x3 should take roughly": "X。 EC1x3 大概需要",
    "x. EC1x4 should take": "X。 EC1x4 应该采取",
    "x. EC3x2 should take": "X。 EC3x2 应该采取",
    "x. Either way, you should now be able to complete the challenge without using all your purchases, and without changing the prestige autobuyer. This challenge takes roughly": "X。无论哪种方式，您现在都应该能够在不使用所有购买且不更改声望自动购买者的情况下完成挑战。这个挑战大约需要",
    "x. Infinities will still be": "X。无穷大仍将是",
    "x. Optionally do some more normal infinities now if you want. Do Normal Challenges 2, 6, 7, 10, and 12, and then, having completed all normal challenges, break infinity in the Infinity tab.": "X。如果你愿意，现在可以选择做一些更正常的无穷大。进行普通挑战 2、6、7、10 和 12，然后在完成所有普通挑战后，在无限选项卡中打破无限。",
    "x. The length of infinities will increase from": "X。无穷大的长度将从",
    "x. The production of boost power helps a lot in this challenge. EC3x3 should take": "X。升压功率的产生对这一挑战有很大帮助。 EC3x3 应该采取",
    "x. When you get": "X。当你拿到时",
    "x) multiplier. Thus, it should only take roughly": "x) 乘数。因此，它应该只需要大致",
    "x). Sacrifice once in each prestige,": "X）。在每个声望中牺牲一次，",
    "you get less than": "你得到的少于",
    "you just got) on": "你刚刚得到）",
    "You may not have the theorem for": "你可能没有定理",
    "You now have": "你现在有",
    "You should soon be able to get": "你应该很快就能得到",
    "You will soon get a third EC autocompletion. You're close to doing EC2x2 yourself and progress is fast, so you should turn autocompletion off. Do EC2x2 at": "您很快将获得第三次 EC 自动补全。您即将自己进行 EC2x2 并且进展很快，因此您应该关闭自动完成功能。做 EC2x2 在",
    "You will soon get more than": "你很快就会得到超过",
    "You won't want to get more than": "你不想得到更多",
    "You'll generally need to get chroma later (in terms of EP) now than pre-complexity, and it will be roughly": "您现在通常需要稍后（就 EP 而言）获得色度，而不是之前的复杂度，它会大致",
    "You'll only have": "你只会有",
    "Your fourth eternity is almost the same as the third, except that, from the": "你的第四永恒与第三永恒几乎相同，除了，从",
    "Your third eternity is a lot like the second, except that, from the": "你的第三个永恒很像第二个永恒，除了，从",
    "ℂP on ℂG2. You can now easily get more completions of several complexity challenges. This complexity, do ℂC4. You could also do ℂC3 at this point, but \"Shadeless\" is such wonderful quality of life and raising the chroma cap is so valuable that ℂC4 is good to do first. Once you complete all ECs, due to not being able to get chroma you can mostly just do eternities that are": "ℂG2 上的ℂP。 您现在可以轻松完成多个复杂挑战的更多完成。 这种复杂性，做ℂC4。 此时你也可以做 ℂC3，但“无影”是如此美妙的生活质量，提高色度上限是如此有价值，所以首先要做 ℂC4。 一旦你完成了所有的 EC，由于无法获得色度，你基本上可以只做永恒的",
    "ℂP on ℂG1, since you're not really saving ℂP for anything right now. Disable buying studies (or in other less precise words, enter ℂC6). Turn EC autocompletion off if you have it on, since you'll be trying to get \"Calm EC\". Note that you'll get enough eternities to gain permanence even before completing": "ℂG1 上的ℂP，因为您现在并没有真正为任何东西节省ℂP。 禁用购买研究（或者用其他不太精确的说法，输入ℂC6）。 如果您打开了 EC 自动完成功能，请关闭它，因为您将尝试获得“Calm EC”。 请注意，即使在完成之前，您也将获得足够的永恒来获得永久性",
    "complexity points. This complexity should be fairly straightforward. At this point you can change the initial part of the Push preset (before &) to 5,6,8,9,10,12,1,2,3,11,4,7. From now on (including in later complexities) this version of the Push preset should be enough to get you through the early part of a complexity, except in some hard complexity challenges such as the upcoming ℂC6. However, using it in some ECs will make them harder. You can either load the preset and respec whenever you can buy a new study, or load only when you can buy the next study in the list; if you constantly load the preset without respeccing, you may buy a later study (for example, Study 7) while unable to afford an earlier one, which is a short-term boost but will be bad eventually if you don't respec.": "复杂点。 这种复杂性应该相当简单。 此时可以将 Push 预设的初始部分（& 之前）更改为 5、6、8、9、10、12、1、2、3、11、4、7。 从现在开始（包括后来的复杂性），这个版本的 Push 预设应该足以让您通过复杂性的早期部分，除了一些困难的复杂性挑战，例如即将到来的 ℂC6。 但是，在某些 EC 中使用它会使它们变得更难。 您可以在可以购买新研究时加载预设和重新指定，或者仅在可以购买列表中的下一个研究时加载； 如果您不断加载预设而不遵守，您可能会购买较晚的研究（例如，研究 7），而无法负担较早的研究，这是一种短期的提升，但如果您不遵守，最终会很糟糕。",
    "complexity points. Save for ℂG2 rather than buying ℂG1 again. Also, enter ℂC4. Also, turn EC autocomplete off if it's on, since you'll be trying to get \"Broke every stone\" this complexity. Even though you don't have chroma, you should be able to do EC8x3, EC6x4, and EC8x4 as soon as you can unlock them. This will give you \"Broke every stone\", which will be very convenient for doing ECs in the future. At": "复杂点。 节省ℂG2，而不是再次购买ℂG1。 另外，输入ℂC4。 此外，如果 EC 自动完成功能已打开，请将其关闭，因为您将试图获得“打破每一块石头”这种复杂性。 即使你没有色度，只要你能解锁它们，你应该可以做 EC8x3、EC6x4 和 EC8x4。 这将给你“打破每一块石头”，这将非常方便将来做EC。 在",
    "each of Generator 1 through Generator 7, then buy max of Generator 8. Then, without turning autobuyers on yet, set autobuyers to buy singles of Generators 1 through Generator 7 and boosts, buy max of Generator 8, sacrifice for some huge unreachable multiplier (like": "发电机 1 到发电机 7 中的每一个，然后购买发电机 8 的最大值。然后，还没有打开自动购买者，设置自动购买者购买发电机 1 到发电机 7 的单件并提升，购买发电机 8 的最大值，牺牲一些巨大的无法达到的乘数（ 喜欢",
    "ℂP, you can, and should, buy a Complexity Generator 1. Complexity generators (ℂGs) are like previous generators except that they cost complexity points. Complexity stars have a single effect, which makes complexity challenge rewards stronger. Note that you start with": "ℂP，您可以并且应该购买复杂度生成器 1。复杂度生成器 (ℂG) 与以前的生成器类似，只是它们需要花费复杂度点。 复杂度之星具有单一效果，这使得复杂度挑战的奖励更强。 请注意，您从",
    "EC autocompletions before you complete all EC tiers. The game is now fast enough that it doesn't matter that much if or when you use them. Towards the end of this complexity, you might notice that you can get chroma even when you use the \"Push\" preset, and thus switching between Chroma and Push can be replaced by just using Push all the time. You should complexity once you get ℂC1x3. This requires": "在您完成所有 EC 层之前，EC 自动完成。 游戏现在已经足够快了，无论何时使用它们都无关紧要。 在这种复杂性接近尾声时，您可能会注意到即使使用“Push”预设也可以获得色度，因此只需始终使用 Push 即可在 Chroma 和 Push 之间切换。 一旦获得ℂC1x3，您就应该变得复杂。 这需要",
    "each. Buy EG2 again, then buy EG1 as it becomes affordable. From now on, advice about buying eternity upgrades and generators is similar to that about buying infinity upgrades and generators. The third and second upgrades start out good (the third especially so) but get worse per purchase; the first starts out bad but gets better per purchase (though it can only be purchased": "每个。 再次购买 EG2，然后购买 EG1，因为它变得负担得起。 从现在开始，购买永恒升级和发电机的建议与购买无限升级和发电机的建议类似。 第三次和第二次升级开始时效果很好（第三次尤其如此），但每次购买都会变得更糟； 第一个开始不好，但每次购买都会变得更好（尽管它只能购买",
    "EC completions and gain IP without needing to infinity, so you can turn your infinity autobuyer off. You can also now view the chroma tab, but it won't be useful for a while. Do EC4x4, unlock and complete whatever (EC4x4 is so easy that you don't need any studies). Replace Study 11 by Study 2 again, since now that you don't need to infinity eternities are shorter (your first few eternities after completing EC8x1 and EC4x4 can be less than": "EC 完成并获得 IP 而无需无限，因此您可以关闭您的无限自动购买。 您现在还可以查看色度选项卡，但暂时不会有用。 做 EC4x4，解锁并完成任何事情（EC4x4 非常简单，您不需要任何学习）。 再次将研究 11 替换为研究 2，因为现在您不需要无限永恒更短（完成 EC8x1 和 EC4x4 后的前几个永恒可能小于",
    "EC completions, you will still get a multiplier to eternity gain, but it won't help you get permanence because gaining permanence requires the Eternity Producer to be unlocked. You'll get an EC autocompletion; EC4x4 is a good choice to use it on (since otherwise you won't complete EC4x4 in ℂC3 at all) but you don't need to use it at all, and if you do use it it's not too important where. You should get \"Actually a boost\" naturally, at roughly": "EC完成后，您仍然可以获得永恒增益的乘数，但它不会帮助您获得永久性，因为获得永久性需要解锁永恒生产者。 你会得到一个 EC 自动补全； EC4x4 是使用它的好选择（因为否则您根本无法在ℂC3 中完成 EC4x4），但您根本不需要使用它，如果您确实使用它，它在哪里并不重要。 你应该自然地得到“实际上是一个提升”，大约是",
    "complexities. This will let you do ℂC3. ℂC1x3 will also let you do a few more tiers of ℂC2. (Later comment: This is true but I'm not sure it's worth the extra time.) So disable buying boosts (do this before you complexity, since otherwise you'll buy boosts before you can disable them) and disable unlocking the Eternity Producer. Technically you could leave unlocking the Eternity Producer enabled and you would remain in ℂC3 until you actually unlock it, but it is good to remove the risk of accidentally unlocking it.": "复杂性。 这会让你做ℂC3。 ℂC1x3 还可以让你做更多的 ℂC2 层。 （后来评论：这是真的，但我不确定这是否值得额外的时间。）所以禁用购买提升（在你复杂之前这样做，否则你会在禁用它们之前购买提升）并禁用解锁永恒生产者 . 从技术上讲，您可以启用解锁 永恒生产者，并且您将一直处于ℂC3 中，直到您真正解锁它，但最好消除意外解锁它的风险。",
    "ℂC2 completions, exit ℂC2. (Note: You may have already got this many in your third complexity, in which case it isn't worth getting them now. In fact, getting \"Forever isn't too long\" in your third complexity necessarily gives you enough ℂC2 completions that it's not clearly worth getting more now.)": "ℂC2 完成，退出ℂC2。 （注意：你可能已经在你的第三个复杂性中得到了这么多，在这种情况下，现在不值得得到它们。事实上，在你的第三个复杂性中得到“永远不会太长”必然会给你足够的 ℂC2 现在显然不值得获得更多的完成。）",
    "but will decrease with additional EP and thus additional eternity stars. You can in fact set your eternity autobuyer to time and get more EP automatically, due to your eternity generator autobuyers and other similar autobuyers. When you get": "但会随着额外的 EP 和额外的永恒星而减少。 实际上，由于您的永恒生成器自动购买者和其他类似的自动购买者，您可以将您的永恒自动购买者设置为时间并自动获得更多 EP。 当你得到",
    "completions each. Most importantly, however, each complexity challenge has a condition rather than being entered explicitly. For as long in a complexity as you observe the condition, you stay in the complexity challenge, and once you break the condition you exit the complexity challenge. Now that you have": "每个完成。 然而，最重要的是，每个复杂性挑战都有一个条件，而不是明确输入。 只要您在复杂性中观察条件，您就一直处于复杂性挑战中，一旦打破条件，您就退出复杂性挑战。 现在你有",
    "complexities and can start doing complexity challenges. Complexity challenges are very different from the previous types of challenges. They have star requirements and do not require you to infinity, eternity, or complexity for completion. They can be completed any number of times (though they get harder each time), like eternity challenges without the limit of": "复杂性，并可以开始进行复杂性挑战。 复杂性挑战与之前的挑战类型有很大不同。 他们有星级要求，不需要你无限、永恒或复杂才能完成。 它们可以完成任意次数（尽管每次都会变得更难），就像没有限制的永恒挑战",
    "complexities. This complexity should be fairly straightforward. You shouldn't try to get any complexity challenge completions. EC1 and EC3 are at this point far harder than the other ECs compared to their original difficulty (so EC3 is still easier than EC2 and EC4 in general, and EC1 is still the easiest, just not by as much). You'll get": "复杂性。 这种复杂性应该相当简单。 您不应该尝试完成任何复杂性挑战。 EC1 和 EC3 在这一点上比其他 EC 的难度要大得多（因此 EC3 总体上仍然比 EC2 和 EC4 容易，而 EC1 仍然是最简单的，只是没有那么多）。 你会得到",
    "EC tiers, and if you leave the game for a few hours you may have more permanence than expected, which may let you do certain EC tiers earlier than you otherwise could. The third permanence upgrade is useless while you're in ℂC6 since you can't buy studies, so so you can turn its autobuyer off if you want, but doing so is not that helpful and the benefits are perhaps outweighed by the fact that you might forget to turn the autobuyer back on.": "EC 层级，如果你离开游戏几个小时，你可能会比预期有更多的持久性，这可能会让你比其他方式更早地完成某些 EC 层级。 当你在ℂC6时，第三次永久升级是没有用的，因为你不能购买研究，所以你可以根据需要关闭它的自动购买，但这样做没有多大帮助，而且好处可能超过了你 可能会忘记重新打开自动购买。",
    "boost power, perhaps by making the eternity somewhat longer (": "增强力量，也许是通过使永恒更长一些（",
    "boost power, so that you can get": "提升动力，这样你就可以得到",
    "boost power, which should take roughly": "提升功率，这应该需要大约",
    "boosts (that is, max(0, boosts reached this eternity -": "boosts（即 max(0, boosts 达到了这个永恒 -",
    "boosts and thus start producing boost power. Each boost reached in the current eternity above": "升压，从而开始产生升压功率。在上述当前永恒中达到的每一次提升",
    "Breaking infinity to starting Infinity Challenge 1": "打破无限开始无限挑战1",
    "but it doesn't matter), do EC8x1, unlock 9, 10, 11, 12, complete 1, 2, 3, 4, 5, 6, 7, 8 (": "不过没关系），做EC8x1，解锁9、10、11、12，完成1、2、3、4、5、6、7、8（",
    "Buy theorems with stars and IP as they become affordable. When you get": "购买带有星星和 IP 的定理，因为它们变得负担得起。当你拿到时",
    "by the end of this). Infinity Challenge 5 now has basically no delay at the start of each prestige.": "到此结束）。无限挑战5现在每个声望的开始基本没有延迟。",
    "ℂC2 completion) roughly": "ℂC2完成）大致",
    "ℂC2 completions without much trouble. Once you get": "ℂC2 完成没有太多麻烦。一旦你得到",
    "ℂC2 completions, exit ℂC2, that is, re-enable buying boosts. Unlocking the Eternity Producer should remain disabled, though. Note that once you have": "ℂC2 完成，退出ℂC2，即重新启用购买提升。不过，解锁 Eternity Producer 应该保持禁用状态。请注意，一旦您拥有",
    "chroma = cap * (": "色度 = 上限 * (",
    "chroma and thus": "色度，因此",
    "Chroma works as follows. Chroma builds up over time in an eternity and resets on eternity, getting": "色度的工作原理如下。色度在永恒中随着时间的推移而积累，并在永恒中重置，获得",
    "Compared to previous IC rewards, the IC3 reward is rather weak. Infinities will still be roughly": "相比之前的 IC 奖励，IC3 的奖励比较弱。无穷大仍将大致",
    "complete 1, 2, 3, 4, 5, 6, 7, 8": "完成 1、2、3、4、5、6、7、8",
    "complete 1, 2, 3, 4, 5, 6, 8": "完成 1、2、3、4、5、6、8",
    "complete 2, 3, 6, 8, 9, 10": "完成 2, 3, 6, 8, 9, 10",
    "complete 3, 4, 7, 8, 9, 12": "完成 3, 4, 7, 8, 9, 12",
    "complete 3, 5, 6, 8, 9, 10": "完成 3、5、6、8、9、10",
    "complete 3, 5, 6, 8, 9, 10, 12": "完成 3、5、6、8、9、10、12",
    "complete 3, 6, 8, 9, 10, 12": "完成 3, 6, 8, 9, 10, 12",
    "complete 3, 7, 8, 9, 12": "完成 3, 7, 8, 9, 12",
    "complete 3, 8, 10, 12": "完成 3、8、10、12",
    "complete 3, 8, 9, 10, 12": "完成 3、8、9、10、12",
    "complete 3, 8, 9, 12": "完成 3、8、9、12",
    "complete 5, 6, 8, 9, 10, 11, 12": "完成 5、6、8、9、10、11、12",
    "complete 5, 6, 8, 9, 10, 12": "完成 5、6、8、9、10、12",
    "complete 6, 8, 9, 10": "完成 6、8、9、10",
    "complete 6, 8, 9, 10, 12": "完成 6、8、9、10、12",
    "complete 8, 10, 11, 12": "完成 8、10、11、12",
    "Completing all complexity achievements to unlocking powers": "完成所有复杂性成就以解锁力量",
    "Completing all eternity milestones to unlocking the Eternity Producer": "完成所有永恒里程碑以解锁永恒生产者",
    "completions of ℂC2, and with them \"One per generator\", roughly": "ℂC2 的补全，并与他们一起“每个生成器一个”，大致",
    "completions of, regardless of which ECs you can unlock, which EC is currently unlocked, or which EC if any you are currently in.": "无论您可以解锁哪些 EC，当前已解锁哪个 EC，或者您当前在哪个 EC（如果有），都已完成。",
    "complexities and": "复杂性和",
    "complexities, you should get some completions of ℂC2, which has the condition that you can't buy boosts. In the Complexity Challenges tab you can disable buying of boosts, and you should do this.": "复杂性，你应该完成一些ℂC2，它的条件是你不能购买提升。在“复杂性挑战”选项卡中，您可以禁用购买提升，您应该这样做。",
    "complexity achievements, in roughly": "复杂性成就，大致在",
    "Complexity Challenge 1 (ℂC1) completion. Complexity challenges will become more relevant and thus more discussed later. For now you can ignore them.": "复杂性挑战 1 (ℂC1) 完成。复杂性挑战将变得更加相关，因此稍后将进行更多讨论。现在你可以忽略它们。",
    "complexity points (ℂP) and": "复杂点 (ℂP) 和",
    "complexity points. Do ℂC3. Get": "复杂点。做ℂC3。得到",
    "complexity points. Do ℂC5. Note that by this point in the game, manual infinities might be faster than using the infinity autobuyer due to being easier to adjust. You should be able to get ℂC5x2 in roughly": "复杂点。做ℂC5。请注意，在游戏的这一点上，手动无穷大可能比使用无穷大自动购买更快，因为它更容易调整。您应该能够大致获得 ℂC5x2",
    "complexity points. Do so as soon as you can. You should be able to get to this point from unlocking cyan in roughly": "复杂点。尽快这样做。您应该能够大致解锁青色到这一点",
    "complexity points. Don't do any complexity challenges for this complexity. Progress will be very quick. Complexity as soon as you can get 3 ℂP. This complexity should take roughly": "复杂点。不要为这种复杂性做任何复杂性挑战。进展会非常快。复杂度只要你能得到 3 ℂP。这种复杂性大约需要",
    "complexity points. Spend": "复杂点。花费",
    "complexity stars at the start of each complexity. Note also that before you eternity you have": "复杂性在每个复杂性的开头出现。还要注意，在你永恒之前，你有",
    "Complexity to completing all complexity achievements": "完成所有复杂性成就的复杂性",
    "ℂP again.": "ℂP。",
    "ℂP and ℂC1x5, both of which require almost exactly the same amount of progress. To do this, your eternities may need to be": "ℂP 和 ℂC1x5，两者都需要几乎完全相同的进度。要做到这一点，你的永恒可能需要",
    "ℂP formula: (total EP this complexity)^": "ℂP公式：（总EP这个复杂度）^",
    "ℂP per complexity for a while, but just for reference, here's the ℂP formula.": "ℂP 每个复杂度一段时间，但仅供参考，这里是 ℂP 公式。",
    "ℂP, at": "ℂP, 在",
    "ℂP, with far less trouble than the first time. You can get here in": "ℂP，比第一次麻烦多了。你可以进去",
    "ℂP; this may feel harder than it did last complexity because you have fewer complexity stars due to getting to the end of your complexity more quickly. This complexity should take roughly": "ℂP;这可能感觉比上次复杂性更难，因为您可以更快地达到复杂性的终点，因此您的复杂性星数更少。这种复杂性大约需要",
    "ℂP. This complexity should take roughly": "ℂP。这种复杂性大约需要",
    "cyan (both also": "青色（两者也",
    "cyan (which takes roughly another": "青色（大约需要另一个",
    "cyan, which should take roughly": "青色，大概需要",
    "Do another long eternity (roughly": "做另一个漫长的永恒（大约",
    "Do another longer eternity, with the infinity autobuyer set to": "做另一个更长的永恒，无限自动购买设置为",
    "Do EC7x3 as soon as you can unlock it (": "解锁后立即执行 EC7x3（",
    "due to EC1 autocompletions, so may not be worth getting and was thus not originally recommended. Specifically, without ℂC1x2,": "由于 EC1 自动完成，因此可能不值得获得，因此最初不推荐。具体来说，没有ℂC1x2，",
    "Due to eternity stars, setting your infinity autobuyer to": "由于永恒之星，将您的无限自动购买设置为",
    "due to how quick progress is. The eternity in which you get EG7 is somewhat long, being roughly": "由于进展如此之快。你得到EG7的永恒有点长，大概是",
    "each). At": "每个）。在",
    "each). When you unlock green, start producing green as you did pre-complexity, using the Chroma preset. Getting chroma of each color is now so quick that you should do it whenever you can't get": "每个）。当您解锁绿色时，使用 Chroma 预设开始产生绿色，就像您在复杂度之前所做的那样。现在获取每种颜色的色度是如此之快，以至于当你无法获得时你应该这样做",
    "each). You should soon be able to complexity for": "每个）。你应该很快就可以复杂化了",
    "EC autocompletion and it doesn't matter much where you use it. Complexity when you can gain": "EC 自动补全，在哪里使用它并不重要。当你可以获得复杂性时",
    "EC completions to get here, or": "EC完成到达这里，或",
    "EC completions, or": "EC完成，或",
    "EC completions, which will give a huge multiplier (": "EC完成，这将产生巨大的乘数（",
    "EC completions. It takes": "EC完成。它需要",
    "EC tiers and \"Calm EC\" should take roughly": "EC 层级和“Calm EC”应该大致",
    "EC tiers completed.": "EC 层已完成。",
    "EC tiers should take roughly": "EC 层应该大约需要",
    "EC1 autocompletions are required for \"Forever isn't too long\"; this will let you get Study 3 and make \"Forever isn't too long\" easy.)": "“永远不会太长”需要 EC1 自动完成；这将使您获得研究 3 并使“永远不会太长”变得容易。）",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);